//! Argon CLI Integration Tests

#[cfg(test)]
mod tests {
    use assert_cmd::Command;
    use predicates::prelude::*;
    use std::fs;
    use std::path::PathBuf;

    #[allow(dead_code)]
    fn test_dir() -> PathBuf {
        PathBuf::from(env!("CARGO_MANIFEST_DIR"))
    }

    #[test]
    fn test_compile_simple() {
        let temp_dir = tempfile::tempdir().unwrap();
        let source_file = temp_dir.path().join("test.arg");
        fs::write(&source_file, "const x = 5;\nconsole.log(x);\n").unwrap();

        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("compile")
            .arg(&source_file)
            .arg("-o")
            .arg(temp_dir.path().join("output.js"))
            .arg("--pipeline")
            .arg("ir")
            .assert()
            .success()
            .stdout(predicate::str::contains("Parsing"))
            .stdout(predicate::str::contains("Type checking"))
            .stdout(predicate::str::contains("Borrow checking"))
            .stdout(predicate::str::contains("Generating JavaScript"))
            .stdout(predicate::str::contains("Done"));

        let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
        assert!(output.contains("Generated by Argon (IR)"));
        assert!(output.contains("const x = 5"));
        assert!(output.contains("console.log(x)"));
    }

    #[test]
    fn test_compile_function() {
        let temp_dir = tempfile::tempdir().unwrap();
        let source_file = temp_dir.path().join("function.arg");
        fs::write(
            &source_file,
            "function add(a: number, b: number): number {\n    return a + b;\n}\nconsole.log(add(1, 2));\n",
        )
        .unwrap();

        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("compile")
            .arg(&source_file)
            .arg("-o")
            .arg(temp_dir.path().join("output.js"))
            .assert()
            .success();

        let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
        assert!(output.contains("function add"));
    }

    #[test]
    fn test_compile_struct() {
        let temp_dir = tempfile::tempdir().unwrap();
        let source_file = temp_dir.path().join("struct.arg");
        fs::write(
            &source_file,
            "struct Point {\n    x: number;\n    y: number;\n}\nconst p = Point { x: 1, y: 2 };\nconsole.log(p.x);\n",
        )
        .unwrap();

        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("compile")
            .arg(&source_file)
            .arg("-o")
            .arg(temp_dir.path().join("output.js"))
            .assert()
            .success();
    }

    #[test]
    fn test_check_validates_borrow_checker() {
        let temp_dir = tempfile::tempdir().unwrap();
        let source_file = temp_dir.path().join("borrow.arg");
        // This should compile successfully with borrow checking
        fs::write(
            &source_file,
            "function test(x: number): void {\n    const y = x;\n}\n",
        )
        .unwrap();

        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("check").arg(&source_file).assert().success();
    }

    #[test]
    fn test_compile_with_declarations() {
        let temp_dir = tempfile::tempdir().unwrap();
        let source_file = temp_dir.path().join("decl.arg");
        fs::write(
            &source_file,
            "function greet(name: string): string {\n    return \"Hello, \" + name;\n}\n",
        )
        .unwrap();

        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("compile")
            .arg(&source_file)
            .arg("-o")
            .arg(temp_dir.path().join("output.js"))
            .arg("--declarations")
            .assert()
            .success();

        let dts = fs::read_to_string(temp_dir.path().join("output.d.ts")).unwrap();
        assert!(dts.contains("greet"));
    }

    #[test]
    fn test_invalid_syntax_fails() {
        let temp_dir = tempfile::tempdir().unwrap();
        let source_file = temp_dir.path().join("invalid.arg");
        fs::write(&source_file, "const x = ;\n").unwrap();

        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("compile")
            .arg(&source_file)
            .arg("-o")
            .arg(temp_dir.path().join("output.js"))
            .assert()
            .failure();
    }

    #[test]
    fn test_help_output() {
        let mut cmd = Command::cargo_bin("argon").unwrap();
        cmd.arg("--help")
            .assert()
            .success()
            .stdout(predicate::str::contains("Argon"));
    }
}
