//! SafeScript - JavaScript code generator

use safescript_ast::*;
use safescript_ir::*;

pub struct JsCodegen {
    output: String,
    indent: usize,
    variables: Vec<String>,
}

impl JsCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            variables: Vec::new(),
        }
    }

    pub fn generate(&mut self, _module: &Module) -> Result<String, CodegenError> {
        Ok(self.output.clone())
    }

    pub fn generate_from_ast(&mut self, source: &SourceFile) -> Result<String, CodegenError> {
        self.output.push_str("// Generated by SafeScript\n\n");

        for stmt in &source.statements {
            self.generate_statement(stmt)?;
        }

        Ok(self.output.clone())
    }

    fn generate_statement(&mut self, stmt: &Stmt) -> Result<(), CodegenError> {
        match stmt {
            Stmt::Variable(v) => self.generate_variable(v),
            Stmt::Function(f) => self.generate_function(f),
            Stmt::AsyncFunction(f) => self.generate_async_function(f),
            Stmt::Struct(s) => self.generate_struct(s),
            Stmt::Class(c) => self.generate_class(c),
            Stmt::Expr(e) => {
                self.generate_expression(&e.expr)?;
                self.output.push_str(";\n");
                Ok(())
            }
            Stmt::Return(r) => {
                self.output.push_str("return");
                if let Some(ref arg) = r.argument {
                    self.output.push_str(" ");
                    self.generate_expression(arg)?;
                }
                self.output.push_str(";\n");
                Ok(())
            }
            Stmt::If(i) => self.generate_if(i),
            Stmt::While(w) => self.generate_while(w),
            Stmt::For(f) => self.generate_for(f),
            Stmt::Block(b) => self.generate_block(b),
            Stmt::Break(_) => {
                self.output.push_str("break;\n");
                Ok(())
            }
            Stmt::Continue(_) => {
                self.output.push_str("continue;\n");
                Ok(())
            }
            Stmt::Match(m) => self.generate_match(m),
            Stmt::Try(t) => self.generate_try(t),
            Stmt::Throw(t) => self.generate_throw(t),
            Stmt::Switch(s) => self.generate_switch(s),
            Stmt::DoWhile(d) => self.generate_do_while(d),
            Stmt::Empty(_) => Ok(()),
            _ => Ok(()),
        }
    }

    fn generate_variable(&mut self, v: &VariableStmt) -> Result<(), CodegenError> {
        let keyword = match v.kind {
            VariableKind::Var => "var",
            VariableKind::Let => "let",
            VariableKind::Const => "const",
        };

        self.output.push_str(keyword);
        self.output.push_str(" ");

        for (i, decl) in v.declarations.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }

            if let Pattern::Identifier(id) = &decl.id {
                self.output.push_str(&id.name.sym);

                if let Some(ref init) = decl.init {
                    self.output.push_str(" = ");
                    self.generate_expression(init)?;
                }
            }
        }
        self.output.push_str(";\n");
        Ok(())
    }

    fn generate_function(&mut self, f: &FunctionDecl) -> Result<(), CodegenError> {
        self.output.push_str("function ");
        if let Some(ref id) = f.id {
            self.output.push_str(&id.sym);
        }
        self.output.push_str("(");

        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if let Pattern::Identifier(id) = &p.pat {
                self.output.push_str(&id.name.sym);
            }
        }
        self.output.push_str(") {\n");

        self.indent += 1;
        for stmt in &f.body.statements {
            self.generate_statement(stmt)?;
        }
        self.indent -= 1;

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_struct(&mut self, s: &StructDecl) -> Result<(), CodegenError> {
        // Generate a constructor function for the struct
        self.output.push_str("function ");
        self.output.push_str(&s.id.sym);
        self.output.push_str("(");

        // Parameters are the field names
        let params: Vec<_> = s.fields.iter().map(|f| f.id.sym.as_str()).collect();
        self.output.push_str(&params.join(", "));
        self.output.push_str(") {\n");

        // Assign fields to this
        for field in &s.fields {
            self.output.push_str("    this.");
            self.output.push_str(&field.id.sym);
            self.output.push_str(" = ");
            self.output.push_str(&field.id.sym);
            self.output.push_str(";\n");
        }

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_class(&mut self, c: &ClassDecl) -> Result<(), CodegenError> {
        // Generate a constructor function for the class
        self.output.push_str("function ");
        self.output.push_str(&c.id.sym);
        self.output.push_str("(");

        // Find constructor and get its params
        let mut has_constructor = false;
        for member in &c.body.body {
            if let ClassMember::Constructor(constr) = member {
                has_constructor = true;
                let params: Vec<_> = constr
                    .params
                    .iter()
                    .map(|p| {
                        if let Pattern::Identifier(id) = &p.pat {
                            id.name.sym.as_str()
                        } else {
                            ""
                        }
                    })
                    .collect();
                self.output.push_str(&params.join(", "));
            }
        }

        if !has_constructor {
            self.output.push_str(")");
        }

        self.output.push_str(") {\n");

        // Generate constructor body
        for member in &c.body.body {
            match member {
                ClassMember::Constructor(constr) => {
                    for stmt in &constr.body.statements {
                        self.generate_statement(stmt)?;
                    }
                }
                ClassMember::Field(field) => {
                    // Generate field initialization if there's a value
                    if let Some(value) = &field.value {
                        self.output.push_str("this.");
                        self.generate_expression(&field.key)?;
                        self.output.push_str(" = ");
                        self.generate_expression(value)?;
                        self.output.push_str(";\n");
                    }
                }
                ClassMember::Method(method) => {
                    // Generate method
                    self.output.push_str("this.");
                    self.generate_expression(&method.key)?;
                    self.output.push_str(" = function(");

                    // Method params
                    let params: Vec<_> = method
                        .value
                        .params
                        .iter()
                        .map(|p| {
                            if let Pattern::Identifier(id) = &p.pat {
                                id.name.sym.as_str()
                            } else {
                                ""
                            }
                        })
                        .collect();
                    self.output.push_str(&params.join(", "));
                    self.output.push_str(") {\n");

                    // Method body
                    for stmt in &method.value.body.statements {
                        self.generate_statement(stmt)?;
                    }

                    self.output.push_str("};\n");
                }
                _ => {
                    // Other class members not supported yet
                }
            }
        }

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_expression(&mut self, expr: &Expr) -> Result<(), CodegenError> {
        match expr {
            Expr::Literal(lit) => self.generate_literal(lit),
            Expr::Identifier(id) => {
                self.output.push_str(&id.sym);
                Ok(())
            }
            Expr::Binary(b) => self.generate_binary(b),
            Expr::Unary(u) => self.generate_unary(u),
            Expr::Call(c) => self.generate_call(c),
            Expr::Member(m) => self.generate_member(m),
            Expr::Assignment(a) => self.generate_assignment(a),
            Expr::This(_) => {
                self.output.push_str("this");
                Ok(())
            }
            Expr::New(n) => {
                self.output.push_str("new ");
                self.generate_expression(&n.callee)?;
                self.output.push_str("(");
                for arg in &n.arguments {
                    if let ExprOrSpread::Expr(e) = arg {
                        self.generate_expression(e)?;
                    }
                }
                self.output.push_str(")");
                Ok(())
            }
            Expr::Conditional(c) => {
                self.output.push_str("(");
                self.generate_expression(&c.test)?;
                self.output.push_str(" ? ");
                self.generate_expression(&c.consequent)?;
                self.output.push_str(" : ");
                self.generate_expression(&c.alternate)?;
                self.output.push_str(")");
                Ok(())
            }
            Expr::Object(o) => self.generate_object(o),
            Expr::Ref(r) => {
                self.generate_expression(&r.expr)?;
                Ok(())
            }
            Expr::MutRef(r) => {
                self.generate_expression(&r.expr)?;
                Ok(())
            }
            _ => {
                self.output.push_str("undefined");
                Ok(())
            }
        }
    }

    fn generate_literal(&mut self, lit: &Literal) -> Result<(), CodegenError> {
        match lit {
            Literal::Number(n) => {
                self.output.push_str(&n.raw);
                Ok(())
            }
            Literal::String(s) => {
                self.output.push_str(&s.value);
                Ok(())
            }
            Literal::Boolean(b) => {
                self.output.push_str(if b.value { "true" } else { "false" });
                Ok(())
            }
            Literal::Null(_) => {
                self.output.push_str("null");
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn generate_binary(&mut self, b: &BinaryExpr) -> Result<(), CodegenError> {
        self.output.push_str("(");
        self.generate_expression(&b.left)?;

        let op = match b.operator {
            BinaryOperator::Plus => "+",
            BinaryOperator::Minus => "-",
            BinaryOperator::Multiply => "*",
            BinaryOperator::Divide => "/",
            BinaryOperator::Modulo => "%",
            BinaryOperator::Equal => "===",
            BinaryOperator::NotEqual => "!==",
            BinaryOperator::StrictEqual => "===",
            BinaryOperator::StrictNotEqual => "!==",
            BinaryOperator::LessThan => "<",
            BinaryOperator::LessThanOrEqual => "<=",
            BinaryOperator::GreaterThan => ">",
            BinaryOperator::GreaterThanOrEqual => ">=",
            BinaryOperator::BitwiseAnd => "&",
            BinaryOperator::BitwiseOr => "|",
            BinaryOperator::BitwiseXor => "^",
            BinaryOperator::LeftShift => "<<",
            BinaryOperator::RightShift => ">>",
            _ => " + ",
        };

        self.output.push_str(&format!(" {} ", op));
        self.generate_expression(&b.right)?;
        self.output.push_str(")");
        Ok(())
    }

    fn generate_unary(&mut self, u: &UnaryExpr) -> Result<(), CodegenError> {
        let op = match u.operator {
            UnaryOperator::Minus => "-",
            UnaryOperator::Plus => "+",
            UnaryOperator::LogicalNot => "!",
            UnaryOperator::BitwiseNot => "~",
            UnaryOperator::Typeof => "typeof ",
            _ => "",
        };
        self.output.push_str(op);
        self.generate_expression(&u.argument)?;
        Ok(())
    }

    fn generate_call(&mut self, c: &CallExpr) -> Result<(), CodegenError> {
        self.generate_expression(&c.callee)?;
        self.output.push_str("(");
        for (i, arg) in c.arguments.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if let ExprOrSpread::Expr(e) = arg {
                self.generate_expression(e)?;
            }
        }
        self.output.push_str(")");
        Ok(())
    }

    fn generate_object(&mut self, o: &ObjectExpression) -> Result<(), CodegenError> {
        self.output.push_str("{ ");
        for (i, prop) in o.properties.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            match prop {
                ObjectProperty::Property(p) => {
                    self.generate_expression(&p.key)?;
                    self.output.push_str(": ");
                    if let ExprOrSpread::Expr(e) = &p.value {
                        self.generate_expression(e)?;
                    }
                }
                ObjectProperty::Shorthand(id) => {
                    self.output.push_str(&id.sym);
                }
                _ => {}
            }
        }
        self.output.push_str(" }");
        Ok(())
    }

    fn generate_member(&mut self, m: &MemberExpr) -> Result<(), CodegenError> {
        self.generate_expression(&m.object)?;

        if m.computed {
            self.output.push_str("[");
            self.generate_expression(&m.property)?;
            self.output.push_str("]");
        } else {
            self.output.push_str(".");
            self.generate_expression(&m.property)?;
        }
        Ok(())
    }

    fn generate_assignment(&mut self, a: &AssignmentExpr) -> Result<(), CodegenError> {
        self.generate_assignment_target(&a.left)?;

        let op = match a.operator {
            AssignmentOperator::Assign => "=",
            AssignmentOperator::PlusAssign => "+=",
            AssignmentOperator::MinusAssign => "-=",
            AssignmentOperator::MultiplyAssign => "*=",
            AssignmentOperator::DivideAssign => "/=",
            _ => "=",
        };

        self.output.push_str(&format!(" {} ", op));
        self.generate_expression(&a.right)?;
        Ok(())
    }

    fn generate_assignment_target(
        &mut self,
        target: &AssignmentTarget,
    ) -> Result<(), CodegenError> {
        match target {
            AssignmentTarget::Simple(expr) => {
                self.generate_expression(expr)?;
            }
            AssignmentTarget::Member(member) => {
                self.generate_expression(&member.object)?;
                self.output.push_str(".");
                self.generate_expression(&member.property)?;
            }
            _ => {
                self.output.push_str("/* target */");
            }
        }
        Ok(())
    }

    fn generate_if(&mut self, i: &IfStmt) -> Result<(), CodegenError> {
        self.output.push_str("if (");
        self.generate_expression(&i.condition)?;
        self.output.push_str(") {\n");

        self.indent += 1;
        self.generate_statement(&i.consequent)?;
        self.indent -= 1;

        if let Some(ref alt) = i.alternate {
            self.output.push_str("} else {\n");
            self.indent += 1;
            self.generate_statement(alt)?;
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_while(&mut self, w: &WhileStmt) -> Result<(), CodegenError> {
        self.output.push_str("while (");
        self.generate_expression(&w.condition)?;
        self.output.push_str(") {\n");

        self.indent += 1;
        self.generate_statement(&w.body)?;
        self.indent -= 1;

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_for(&mut self, f: &ForStmt) -> Result<(), CodegenError> {
        self.output.push_str("for (");

        if let Some(ref init) = f.init {
            match init {
                ForInit::Variable(v) => self.generate_variable(v)?,
                ForInit::Expr(e) => self.generate_expression(e)?,
            }
        }

        self.output.push_str("; ");

        if let Some(ref test) = f.test {
            self.generate_expression(test)?;
        }

        self.output.push_str("; ");

        if let Some(ref update) = f.update {
            self.generate_expression(update)?;
        }

        self.output.push_str(") {\n");

        self.indent += 1;
        self.generate_statement(&f.body)?;
        self.indent -= 1;

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_block(&mut self, b: &BlockStmt) -> Result<(), CodegenError> {
        self.output.push_str("{\n");
        self.indent += 1;

        for stmt in &b.statements {
            self.generate_statement(stmt)?;
        }

        self.indent -= 1;
        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_match(&mut self, m: &MatchStmt) -> Result<(), CodegenError> {
        self.output.push_str("switch (");
        self.generate_expression(&m.discriminant)?;
        self.output.push_str(") {\n");

        for case in &m.cases {
            self.output.push_str("case ");
            self.generate_expression(&case.pattern)?;
            self.output.push_str(":\n");

            self.indent += 1;
            self.generate_statement(case.consequent.as_ref())?;
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_async_function(&mut self, f: &FunctionDecl) -> Result<(), CodegenError> {
        self.output.push_str("async function ");
        if let Some(ref id) = f.id {
            self.output.push_str(&id.sym);
        }
        self.output.push_str("(");

        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if let Pattern::Identifier(id) = &p.pat {
                self.output.push_str(&id.name.sym);
            }
        }
        self.output.push_str(") {\n");

        self.indent += 1;
        for stmt in &f.body.statements {
            self.generate_statement(stmt)?;
        }
        self.indent -= 1;

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_try(&mut self, t: &TryStmt) -> Result<(), CodegenError> {
        self.output.push_str("try {\n");
        self.indent += 1;
        for stmt in &t.block.statements {
            self.generate_statement(stmt)?;
        }
        self.indent -= 1;

        if let Some(ref handler) = t.handler {
            self.output.push_str("} catch ");
            if let Some(ref param) = handler.param {
                self.output.push_str("(");
                if let Pattern::Identifier(id) = param {
                    self.output.push_str(&id.name.sym);
                }
                self.output.push_str(") ");
            }
            self.output.push_str("{\n");
            self.indent += 1;
            for stmt in &handler.body.statements {
                self.generate_statement(stmt)?;
            }
            self.indent -= 1;
        }

        if let Some(ref finalizer) = t.finalizer {
            self.output.push_str("} finally {\n");
            self.indent += 1;
            for stmt in &finalizer.statements {
                self.generate_statement(stmt)?;
            }
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_throw(&mut self, t: &ThrowStmt) -> Result<(), CodegenError> {
        self.output.push_str("throw ");
        self.generate_expression(&t.argument)?;
        self.output.push_str(";\n");
        Ok(())
    }

    fn generate_switch(&mut self, s: &SwitchStmt) -> Result<(), CodegenError> {
        self.output.push_str("switch (");
        self.generate_expression(&s.discriminant)?;
        self.output.push_str(") {\n");

        for case in &s.cases {
            if let Some(ref test) = case.test {
                self.output.push_str("case ");
                self.generate_expression(test)?;
                self.output.push_str(":\n");
            } else {
                self.output.push_str("default:\n");
            }

            self.indent += 1;
            for stmt in &case.consequent {
                self.generate_statement(stmt)?;
            }
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_do_while(&mut self, d: &DoWhileStmt) -> Result<(), CodegenError> {
        self.output.push_str("do {\n");
        self.indent += 1;
        self.generate_statement(&d.body)?;
        self.indent -= 1;
        self.output.push_str("} while (");
        self.generate_expression(&d.condition)?;
        self.output.push_str(");\n");
        Ok(())
    }

    fn indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }
}

#[derive(Debug)]
pub enum CodegenError {
    Unsupported(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::Unsupported(msg) => write!(f, "Unsupported: {}", msg),
        }
    }
}

impl std::error::Error for CodegenError {}

#[cfg(test)]
mod codegen_tests;
