//! Argon - JavaScript code generator

use argon_ast::*;
use argon_ir::*;

mod expr;
mod ir_codegen;
mod jsx;
mod runtime;
mod std_intrinsics;
mod stmt;

pub struct JsCodegen {
    output: String,
    indent: usize,
    #[allow(dead_code)] // TODO: use for variable scope tracking in codegen
    variables: Vec<String>,
    include_runtime: bool,
    #[allow(dead_code)] // TODO: complete source map generation
    source_map_enabled: bool,
    current_generated_line: usize,
    loop_label_counter: usize,
    skill_defs: std::collections::HashMap<String, SkillDecl>,
}

impl Default for JsCodegen {
    fn default() -> Self {
        Self::new()
    }
}

impl JsCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            variables: Vec::new(),
            include_runtime: true,
            source_map_enabled: false,
            current_generated_line: 0,
            loop_label_counter: 0,
            skill_defs: std::collections::HashMap::new(),
        }
    }

    pub fn with_source_map(mut self, source_name: &str) -> Self {
        let _ = source_name; // Will be used when full sourcemap is implemented
        self.source_map_enabled = true;
        self
    }

    pub fn with_runtime(mut self, include: bool) -> Self {
        self.include_runtime = include;
        self
    }

    pub fn generate(&mut self, _module: &Module) -> Result<String, CodegenError> {
        // Reset state for each generation.
        self.output.clear();
        self.indent = 0;
        self.current_generated_line = 0;
        self.loop_label_counter = 0;

        self.output.push_str("// Generated by Argon (IR)\n\n");

        // ESM-safe ordering: imports first, then runtime, then generated code.
        for import in &_module.imports {
            self.generate_import(import)?;
        }

        if self.include_runtime {
            // Runtime is currently an IIFE; in ESM contexts this must run with `globalThis` (handled in stdlib).
            let runtime = runtime::get_runtime();
            self.output.push_str(runtime);
            self.output.push('\n');
        }

        // Emit struct constructors.
        for ty in &_module.types {
            if let TypeDef::Struct { name, fields } = ty {
                self.output.push_str("function ");
                self.output.push_str(name);
                self.output.push_str("(init) {\n");
                for f in fields {
                    self.output.push_str("    this.");
                    self.output.push_str(&f.name);
                    self.output.push_str(" = init.");
                    self.output.push_str(&f.name);
                    self.output.push_str(";\n");
                }
                self.output.push_str("}\n\n");
            }
        }

        // Emit module-scope globals before any init IIFE.
        for g in &_module.globals {
            self.output.push_str(match g.kind {
                argon_ir::VarKind::Var => "var ",
                argon_ir::VarKind::Let => "let ",
                argon_ir::VarKind::Const => "const ",
            });
            self.output.push_str(&g.name);
            if let Some(v) = g.init {
                let expr = self.ir_eval_expr(&g.init_insts, v)?;
                self.output.push_str(" = ");
                self.output.push_str(&expr);
            } else if matches!(g.kind, argon_ir::VarKind::Const) {
                // JS doesn't allow `const x;`; keep output valid.
                self.output.push_str(" = undefined");
            }
            self.output.push_str(";\n");
        }
        if !_module.globals.is_empty() {
            self.output.push('\n');
        }

        // Emit all non-init functions.
        for func in &_module.functions {
            if func.id == "__argon_init" {
                continue;
            }
            self.generate_ir_function(func)?;
        }

        // Emit init function as an IIFE so top-level statements execute.
        if let Some(init) = _module.functions.iter().find(|f| f.id == "__argon_init") {
            self.generate_ir_init(init)?;
        }

        // Exports last.
        for export in &_module.exports {
            if export.is_type_only {
                // Type-only exports are erased from JS output.
                continue;
            }
            if export.declaration.is_some() {
                return Err(CodegenError::Unsupported(
                    "export declarations must be lowered into IR module items before codegen"
                        .to_string(),
                ));
            }

            self.output.push_str("export { ");
            for (i, spec) in export.specifiers.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.output.push_str(&spec.orig.sym);
                if let Some(ref exported) = spec.exported {
                    self.output.push_str(" as ");
                    self.output.push_str(&exported.sym);
                }
            }
            self.output.push_str(" }");

            if let Some(ref source) = export.source {
                self.output.push_str(" from ");
                self.output
                    .push_str(&Self::rewrite_import_source(&source.value));
            }

            self.output.push_str(";\n");
        }

        Ok(self.output.clone())
    }

    fn ir_eval_expr(
        &self,
        instructions: &[argon_ir::Instruction],
        value: argon_ir::ValueId,
    ) -> Result<String, CodegenError> {
        use argon_ir::Instruction as IrInst;

        let mut values: std::collections::HashMap<argon_ir::ValueId, String> =
            std::collections::HashMap::new();

        for inst in instructions {
            match inst {
                IrInst::ObjectLit { dest, props } => {
                    let mut parts = Vec::new();
                    for p in props {
                        let v = values
                            .get(&p.value)
                            .cloned()
                            .unwrap_or_else(|| "undefined".to_string());
                        parts.push(format!("{}: {}", p.key, v));
                    }
                    values.insert(*dest, format!("{{ {} }}", parts.join(", ")));
                }
                IrInst::New { callee, args, dest } => {
                    let callee = values
                        .get(callee)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let args = args
                        .iter()
                        .map(|a| {
                            values
                                .get(a)
                                .cloned()
                                .unwrap_or_else(|| "undefined".to_string())
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("new {}({})", callee, args));
                }
                IrInst::Await { arg, dest } => {
                    let arg = values
                        .get(arg)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("await {}", arg));
                }
                IrInst::AssignExpr { name, src, dest } => {
                    let expr = values
                        .get(src)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({} = {})", name, expr));
                }
                IrInst::Const { dest, value } => {
                    values.insert(*dest, self.const_to_js(value));
                }
                IrInst::VarRef { dest, name } => {
                    values.insert(*dest, name.clone());
                }
                IrInst::Member {
                    object,
                    property,
                    dest,
                } => {
                    let obj = values
                        .get(object)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("{}.{}", obj, property));
                }
                IrInst::MemberComputed {
                    object,
                    property,
                    dest,
                } => {
                    let obj = values
                        .get(object)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let prop = values
                        .get(property)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("{}[{}]", obj, prop));
                }
                IrInst::BinOp { op, lhs, rhs, dest } => {
                    let lhs = values
                        .get(lhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let rhs = values
                        .get(rhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(
                        *dest,
                        format!("({} {} {})", lhs, self.binop_to_js(*op), rhs),
                    );
                }
                IrInst::UnOp { op, arg, dest } => {
                    let arg = values
                        .get(arg)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({}{})", self.unop_to_js(*op), arg));
                }
                IrInst::Call { callee, args, dest } => {
                    let callee = values
                        .get(callee)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let args = args
                        .iter()
                        .map(|a| {
                            values
                                .get(a)
                                .cloned()
                                .unwrap_or_else(|| "undefined".to_string())
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("{}({})", callee, args));
                }
                IrInst::ArrayLit { dest, elements } => {
                    let parts = elements
                        .iter()
                        .map(|e| {
                            e.and_then(|id| values.get(&id).cloned())
                                .unwrap_or_else(|| "undefined".to_string())
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("[{}]", parts));
                }
                IrInst::LogicalOp { op, lhs, rhs, dest } => {
                    let lhs = values
                        .get(lhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let rhs = values
                        .get(rhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let op_str = match op {
                        argon_ir::LogicOp::And => "&&",
                        argon_ir::LogicOp::Or => "||",
                        argon_ir::LogicOp::Nullish => "??",
                    };
                    values.insert(*dest, format!("({} {} {})", lhs, op_str, rhs));
                }
                IrInst::Conditional {
                    cond,
                    then_value,
                    else_value,
                    dest,
                } => {
                    let cond = values
                        .get(cond)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let then_value = values
                        .get(then_value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let else_value = values
                        .get(else_value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(
                        *dest,
                        format!("({} ? {} : {})", cond, then_value, else_value),
                    );
                }
                _ => {
                    return Err(CodegenError::Unsupported(format!(
                        "unsupported IR instruction in global initializer: {:?}",
                        inst
                    )));
                }
            }
        }

        Ok(values
            .get(&value)
            .cloned()
            .unwrap_or_else(|| "undefined".to_string()))
    }

    fn next_temp_id(&mut self) -> usize {
        let id = self.loop_label_counter;
        self.loop_label_counter += 1;
        id
    }

    pub fn generate_from_ast(&mut self, source: &SourceFile) -> Result<String, CodegenError> {
        self.output.clear();
        self.indent = 0;
        self.current_generated_line = 0;
        self.skill_defs.clear();

        // Pre-collect skill declarations for struct generation
        for stmt in &source.statements {
            if let Stmt::Skill(sk) = stmt {
                self.skill_defs.insert(sk.id.sym.clone(), sk.clone());
            }
        }

        self.output.push_str("// Generated by Argon\n\n");

        for stmt in &source.statements {
            if matches!(stmt, Stmt::Import(_)) {
                self.generate_statement(stmt)?;
            }
        }

        let runtime_line_count = if self.include_runtime {
            let runtime = runtime::get_runtime();
            self.output.push_str(runtime);
            self.output.push('\n');
            runtime.lines().count() + 1
        } else {
            1
        };

        // Track that we've generated the runtime (or header)
        self.current_generated_line = runtime_line_count;

        for stmt in &source.statements {
            if !matches!(stmt, Stmt::Import(_)) {
                self.generate_statement(stmt)?;
            }
        }

        Ok(self.output.clone())
    }

    pub fn get_source_map(&self) -> Option<String> {
        if self.source_map_enabled {
            Some(r#"{"version":3,"sources":["source"],"names":[],"mappings":""}"#.to_string())
        } else {
            None
        }
    }

    fn add_line(&mut self) {
        self.current_generated_line += 1;
    }
}

#[derive(Debug)]
pub enum CodegenError {
    Unsupported(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::Unsupported(msg) => write!(f, "Unsupported: {}", msg),
        }
    }
}

impl std::error::Error for CodegenError {}

pub fn generate_type_declarations(source: &SourceFile) -> String {
    let mut output = String::new();
    output.push_str("// TypeScript declarations generated by Argon\n\n");

    for stmt in &source.statements {
        append_declaration_stmt(&mut output, stmt, false);
    }

    output
}

fn append_declaration_stmt(output: &mut String, stmt: &Stmt, exported: bool) {
    match stmt {
        Stmt::Function(f) | Stmt::AsyncFunction(f) => {
            if exported {
                output.push_str("export ");
            }
            output.push_str("declare function ");
            if let Some(ref id) = f.id {
                output.push_str(&id.sym);
            }
            append_type_params(output, &f.type_params);
            output.push('(');
            append_params(output, &f.params);
            output.push_str("): ");
            output.push_str(&function_return_type_to_ts_string(f));
            output.push_str(";\n");
        }
        Stmt::Variable(v) => {
            for decl in &v.declarations {
                if exported {
                    output.push_str("export ");
                }
                output.push_str("declare ");
                match v.kind {
                    VariableKind::Var => output.push_str("var "),
                    VariableKind::Let => output.push_str("let "),
                    VariableKind::Const => output.push_str("const "),
                };
                if let Pattern::Identifier(id) = &decl.id {
                    output.push_str(&id.name.sym);
                    if let Some(ref ty) = id.type_annotation {
                        output.push_str(": ");
                        output.push_str(&type_to_ts_string(ty));
                    }
                }
                output.push_str(";\n");
            }
        }
        Stmt::Struct(s) => {
            if exported {
                output.push_str("export ");
            }
            output.push_str("declare class ");
            output.push_str(&s.id.sym);
            append_type_params(output, &s.type_params);
            output.push_str(" {\n");
            // Constructor
            output.push_str("    constructor(init: { ");
            for (i, field) in s.fields.iter().enumerate() {
                if i > 0 {
                    output.push_str("; ");
                }
                output.push_str(&field.id.sym);
                output.push_str(": ");
                output.push_str(&type_to_ts_string(&field.type_annotation));
            }
            output.push_str(" });\n");
            // Fields
            for field in &s.fields {
                output.push_str("    ");
                output.push_str(&field.id.sym);
                output.push_str(": ");
                output.push_str(&type_to_ts_string(&field.type_annotation));
                output.push_str(";\n");
            }
            // Methods
            for method in &s.methods {
                output.push_str("    ");
                if let Expr::Identifier(id) = &method.key {
                    output.push_str(&id.sym);
                }
                output.push('(');
                append_params(output, &method.value.params);
                output.push_str("): ");
                output.push_str(&function_return_type_to_ts_string(&method.value));
                output.push_str(";\n");
            }
            output.push_str("}\n");
        }
        Stmt::Enum(e) => {
            if exported {
                output.push_str("export ");
            }
            output.push_str("declare enum ");
            output.push_str(&e.id.sym);
            output.push_str(" {\n");
            for member in &e.members {
                output.push_str("    ");
                output.push_str(&member.id.sym);
                if let Some(ref init) = member.init {
                    output.push_str(" = ");
                    append_enum_initializer(output, init);
                }
                output.push_str(",\n");
            }
            output.push_str("}\n");
        }
        Stmt::Skill(sk) => {
            if exported {
                output.push_str("export ");
            }
            output.push_str("declare interface ");
            output.push_str(&sk.id.sym);
            output.push_str(" {\n");
            for item in &sk.items {
                match item {
                    SkillItem::ConcreteMethod(sig) => {
                        output.push_str("    ");
                        if let Expr::Identifier(id) = &sig.key {
                            output.push_str(&id.sym);
                        }
                        output.push('(');
                        append_params(output, &sig.value.params);
                        output.push_str("): ");
                        output.push_str(&function_return_type_to_ts_string(&sig.value));
                        output.push_str(";\n");
                    }
                    SkillItem::AbstractMethod(sig) => {
                        output.push_str("    ");
                        output.push_str(&sig.id.sym);
                        output.push('(');
                        append_params(output, &sig.params);
                        output.push_str("): ");
                        if let Some(ref ret) = sig.return_type {
                            output.push_str(&type_to_ts_string(ret));
                        } else {
                            output.push_str("void");
                        }
                        output.push_str(";\n");
                    }
                    SkillItem::RequiredField(_) => {}
                }
            }
            output.push_str("}\n");
        }
        Stmt::TypeAlias(t) => {
            if exported {
                output.push_str("export ");
            }
            output.push_str("type ");
            output.push_str(&t.id.sym);
            append_type_params(output, &t.type_params);
            output.push_str(" = ");
            output.push_str(&type_to_ts_string(&t.type_annotation));
            output.push_str(";\n\n");
        }
        Stmt::Export(e) => {
            if let Some(ref decl) = e.declaration {
                append_declaration_stmt(output, decl, true);
            }
        }
        _ => {}
    }
}

fn append_params(output: &mut String, params: &[argon_ast::Param]) {
    for (i, p) in params.iter().enumerate() {
        if i > 0 {
            output.push_str(", ");
        }
        if let Pattern::Identifier(id) = &p.pat {
            output.push_str(&id.name.sym);
            if p.is_optional {
                output.push('?');
            }
            if let Some(ref ty) = p.ty {
                output.push_str(": ");
                output.push_str(&type_to_ts_string(ty));
            }
        }
    }
}

fn append_type_params(output: &mut String, params: &[TypeParam]) {
    if params.is_empty() {
        return;
    }

    output.push('<');
    for (i, param) in params.iter().enumerate() {
        if i > 0 {
            output.push_str(", ");
        }
        output.push_str(&param.name.sym);
        if let Some(ref constraint) = param.constraint {
            output.push_str(" extends ");
            output.push_str(&type_to_ts_string(constraint));
        }
        if let Some(ref default) = param.default {
            output.push_str(" = ");
            output.push_str(&type_to_ts_string(default));
        }
    }
    output.push('>');
}

fn append_enum_initializer(output: &mut String, expr: &Expr) {
    match expr {
        Expr::Literal(Literal::Number(n)) => output.push_str(&n.raw),
        Expr::Literal(Literal::String(s)) => output.push_str(&s.value),
        Expr::Literal(Literal::Boolean(b)) => {
            output.push_str(if b.value { "true" } else { "false" });
        }
        Expr::Identifier(id) => output.push_str(&id.sym),
        _ => output.push('0'),
    }
}

fn function_return_type_to_ts_string(f: &FunctionDecl) -> String {
    let base = f
        .return_type
        .as_ref()
        .map(|ret_ty| type_to_ts_string(ret_ty))
        .unwrap_or_else(|| "void".to_string());

    if f.is_async {
        format!("Promise<{}>", base)
    } else {
        base
    }
}

fn type_to_ts_string(ty: &argon_ast::Type) -> String {
    match ty {
        argon_ast::Type::Parenthesized(p) => type_to_ts_string(p),
        argon_ast::Type::Any(_) => "any".to_string(),
        argon_ast::Type::Unknown(_) => "unknown".to_string(),
        argon_ast::Type::Never(_) => "never".to_string(),
        argon_ast::Type::Void(_) => "void".to_string(),
        argon_ast::Type::Null(_) => "null".to_string(),
        argon_ast::Type::Undefined(_) => "undefined".to_string(),
        argon_ast::Type::Number(_) => "number".to_string(),
        argon_ast::Type::String(_) => "string".to_string(),
        argon_ast::Type::Boolean(_) => "boolean".to_string(),
        argon_ast::Type::BigInt(_) => "bigint".to_string(),
        argon_ast::Type::Symbol(_) => "symbol".to_string(),
        argon_ast::Type::ThisType(_) => "this".to_string(),
        argon_ast::Type::Primitive(p) => match p {
            PrimitiveType::Number => "number".to_string(),
            PrimitiveType::String => "string".to_string(),
            PrimitiveType::Boolean => "boolean".to_string(),
            PrimitiveType::Void => "void".to_string(),
            PrimitiveType::Null => "null".to_string(),
            PrimitiveType::Undefined => "undefined".to_string(),
            PrimitiveType::Any => "any".to_string(),
            PrimitiveType::Unknown => "unknown".to_string(),
            PrimitiveType::Never => "never".to_string(),
            _ => "any".to_string(),
        },
        argon_ast::Type::Reference(r) => {
            if let TypeName::Ident(id) = &r.name {
                if r.type_args.is_empty() {
                    id.sym.clone()
                } else {
                    let args: Vec<String> = r.type_args.iter().map(type_to_ts_string).collect();
                    format!("{}<{}>", id.sym, args.join(", "))
                }
            } else {
                "any".to_string()
            }
        }
        argon_ast::Type::Array(arr) => {
            format!("{}[]", type_to_ts_string(&arr.elem_type))
        }
        argon_ast::Type::Ref(r) => type_to_ts_string(&r.ty),
        argon_ast::Type::MutRef(r) => type_to_ts_string(&r.ty),
        argon_ast::Type::Shared(s) => {
            format!("Shared<{}>", type_to_ts_string(&s.ty))
        }
        argon_ast::Type::Optional(o) => {
            format!("{} | null", type_to_ts_string(&o.ty))
        }
        argon_ast::Type::Function(f) => {
            let params: Vec<String> = f.params.iter().map(|p| type_to_ts_string(&p.ty)).collect();
            format!(
                "({}) => {}",
                params.join(", "),
                type_to_ts_string(&f.return_type)
            )
        }
        argon_ast::Type::Union(u) => {
            let types: Vec<String> = u.types.iter().map(type_to_ts_string).collect();
            types.join(" | ")
        }
        argon_ast::Type::Intersection(i) => {
            let types: Vec<String> = i.types.iter().map(type_to_ts_string).collect();
            types.join(" & ")
        }
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod codegen_tests;
