//! Argon - JavaScript code generator

use argon_ast::*;
use argon_ir::*;
use argon_stdlib::StdLib;

pub struct JsCodegen {
    output: String,
    indent: usize,
    #[allow(dead_code)]
    variables: Vec<String>,
    include_runtime: bool,
    #[allow(dead_code)]
    source_map_enabled: bool,
    current_generated_line: usize,
}

impl JsCodegen {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
            variables: Vec::new(),
            include_runtime: true,
            source_map_enabled: false,
            current_generated_line: 0,
        }
    }

    pub fn with_source_map(mut self, source_name: &str) -> Self {
        let _ = source_name; // Will be used when full sourcemap is implemented
        self.source_map_enabled = true;
        self
    }

    pub fn with_runtime(mut self, include: bool) -> Self {
        self.include_runtime = include;
        self
    }

    pub fn generate(&mut self, _module: &Module) -> Result<String, CodegenError> {
        // Reset state for each generation.
        self.output.clear();
        self.indent = 0;
        self.current_generated_line = 0;

        self.output.push_str("// Generated by Argon (IR)\n\n");

        // ESM-safe ordering: imports first, then runtime, then generated code.
        for import in &_module.imports {
            self.generate_import(import)?;
        }

        if self.include_runtime {
            // Runtime is currently an IIFE; in ESM contexts this must run with `globalThis` (handled in stdlib).
            let runtime = StdLib::get_runtime();
            self.output.push_str(runtime);
            self.output.push_str("\n");
        }

        // Emit struct constructors.
        for ty in &_module.types {
            if let TypeDef::Struct { name, fields } = ty {
                self.output.push_str("function ");
                self.output.push_str(name);
                self.output.push_str("(init) {\n");
                for f in fields {
                    self.output.push_str("    this.");
                    self.output.push_str(&f.name);
                    self.output.push_str(" = init.");
                    self.output.push_str(&f.name);
                    self.output.push_str(";\n");
                }
                self.output.push_str("}\n\n");
            }
        }

        // Emit all non-init functions.
        for func in &_module.functions {
            if func.id == "__argon_init" {
                continue;
            }
            self.generate_ir_function(func)?;
        }

        // Emit init function as an IIFE so top-level statements execute.
        if let Some(init) = _module.functions.iter().find(|f| f.id == "__argon_init") {
            self.generate_ir_init(init)?;
        }

        // Exports last.
        for export in &_module.exports {
            if export.is_type_only {
                // Type-only exports are erased from JS output.
                continue;
            }
            if export.declaration.is_some() {
                return Err(CodegenError::Unsupported(
                    "export declarations must be lowered into IR module items before codegen"
                        .to_string(),
                ));
            }

            self.output.push_str("export { ");
            for (i, spec) in export.specifiers.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.output.push_str(&spec.orig.sym);
                if let Some(ref exported) = spec.exported {
                    self.output.push_str(" as ");
                    self.output.push_str(&exported.sym);
                }
            }
            self.output.push_str(" }");

            if let Some(ref source) = export.source {
                self.output.push_str(" from ");
                self.output.push_str(&source.value);
            }

            self.output.push_str(";\n");
        }

        Ok(self.output.clone())
    }

    pub fn generate_from_ast(&mut self, source: &SourceFile) -> Result<String, CodegenError> {
        let runtime_line_count = if self.include_runtime {
            let runtime = StdLib::get_runtime();
            self.output.push_str("// Generated by Argon\n\n");
            self.output.push_str(runtime);
            self.output.push_str("\n");
            runtime.lines().count()
        } else {
            self.output.push_str("// Generated by Argon\n\n");
            1
        };

        // Track that we've generated the runtime (or header)
        self.current_generated_line = runtime_line_count;

        for stmt in &source.statements {
            self.generate_statement(stmt)?;
        }

        Ok(self.output.clone())
    }

    pub fn get_source_map(&self) -> Option<String> {
        if self.source_map_enabled {
            Some(r#"{"version":3,"sources":["source"],"names":[],"mappings":""}"#.to_string())
        } else {
            None
        }
    }

    fn add_line(&mut self) {
        self.current_generated_line += 1;
    }

    fn generate_ir_init(&mut self, func: &argon_ir::Function) -> Result<(), CodegenError> {
        if func.body.len() == 1 && matches!(func.body[0].terminator, argon_ir::Terminator::Return(_))
        {
            let entry = func.body.first().ok_or_else(|| {
                CodegenError::Unsupported("init function has no body".to_string())
            })?;
            self.output.push_str("(() => {\n");
            self.generate_ir_block(entry, true)?;
            self.output.push_str("})();\n\n");
            return Ok(());
        }

        self.output.push_str("(() => {\n");
        self.generate_ir_cfg(func, true)?;
        self.output.push_str("})();\n\n");
        Ok(())
    }

    fn generate_ir_function(&mut self, func: &argon_ir::Function) -> Result<(), CodegenError> {
        if func.body.len() == 1 && matches!(func.body[0].terminator, argon_ir::Terminator::Return(_))
        {
            let entry = func.body.first().ok_or_else(|| {
                CodegenError::Unsupported("function has no body".to_string())
            })?;

            if func.is_async {
                self.output.push_str("async ");
            }
            self.output.push_str("function ");
            self.output.push_str(&func.id);
            self.output.push_str("(");
            for (i, p) in func.params.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.output.push_str(&p.name);
            }
            self.output.push_str(") {\n");
            self.generate_ir_block(entry, false)?;
            self.output.push_str("}\n\n");
            return Ok(());
        }

        self.generate_ir_cfg(func, false)
    }

    fn generate_ir_cfg(
        &mut self,
        func: &argon_ir::Function,
        is_init: bool,
    ) -> Result<(), CodegenError> {
        use argon_ir::Terminator as IrTerm;

        if !is_init {
            if func.is_async {
                self.output.push_str("async ");
            }
            self.output.push_str("function ");
            self.output.push_str(&func.id);
            self.output.push_str("(");
            for (i, p) in func.params.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.output.push_str(&p.name);
            }
            self.output.push_str(") {\n");
        }

        let entry_id = func
            .body
            .first()
            .ok_or_else(|| CodegenError::Unsupported("function has no body".to_string()))?
            .id;

        self.output
            .push_str(&format!("    let __bb = {};\n", entry_id));
        self.output.push_str("    while (true) {\n");
        self.output.push_str("        switch (__bb) {\n");

        for block in &func.body {
            self.output
                .push_str(&format!("        case {}: {{\n", block.id));

            let mut values: std::collections::HashMap<argon_ir::ValueId, String> =
                std::collections::HashMap::new();
            self.emit_ir_instructions_cfg_with_prefix(&block.instructions, &mut values, "            ")?;

            match &block.terminator {
                IrTerm::Jump(target) => {
                    self.output
                        .push_str(&format!("            __bb = {};\n", target));
                    self.output.push_str("            continue;\n");
                }
                IrTerm::Branch { cond, then, else_ } => {
                    let cond_expr = values
                        .get(cond)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    self.output
                        .push_str(&format!("            if ({}) {{\n", cond_expr));
                    self.output
                        .push_str(&format!("                __bb = {};\n", then));
                    self.output.push_str("            } else {\n");
                    self.output
                        .push_str(&format!("                __bb = {};\n", else_));
                    self.output.push_str("            }\n");
                    self.output.push_str("            continue;\n");
                }
                IrTerm::Return(Some(v)) => {
                    let expr = values.get(v).cloned().unwrap_or_else(|| "undefined".to_string());
                    self.output
                        .push_str(&format!("            return {};\n", expr));
                }
                IrTerm::Return(None) => {
                    self.output.push_str("            return;\n");
                }
                IrTerm::Unreachable => {
                    self.output
                        .push_str("            throw new Error(\"unreachable\");\n");
                }
            }

            self.output.push_str("        }\n");
        }

        self.output.push_str("        default: {\n");
        self.output
            .push_str("            throw new Error(\"invalid basic block\");\n");
        self.output.push_str("        }\n");
        self.output.push_str("        }\n");
        self.output.push_str("    }\n");

        if !is_init {
            self.output.push_str("}\n\n");
        }

        Ok(())
    }

    fn emit_ir_instructions_cfg_with_prefix(
        &mut self,
        instructions: &[argon_ir::Instruction],
        values: &mut std::collections::HashMap<argon_ir::ValueId, String>,
        prefix: &str,
    ) -> Result<(), CodegenError> {
        use argon_ir::Instruction as IrInst;

        for inst in instructions {
            match inst {
                IrInst::ObjectLit { dest, props } => {
                    let mut parts = Vec::new();
                    for p in props {
                        let v = values
                            .get(&p.value)
                            .cloned()
                            .unwrap_or_else(|| "undefined".to_string());
                        parts.push(format!("{}: {}", p.key, v));
                    }
                    values.insert(*dest, format!("{{ {} }}", parts.join(", ")));
                }
                IrInst::New { callee, args, dest } => {
                    let callee = values
                        .get(callee)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let args = args
                        .iter()
                        .map(|a| values.get(a).cloned().unwrap_or_else(|| "undefined".to_string()))
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("new {}({})", callee, args));
                }
                IrInst::Await { arg, dest } => {
                    let arg = values
                        .get(arg)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("await {}", arg));
                }
                IrInst::AssignExpr { name, src, dest } => {
                    let expr =
                        values.get(src).cloned().unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({} = {})", name, expr));
                }
                IrInst::Const { dest, value } => {
                    values.insert(*dest, self.const_to_js(value));
                }
                IrInst::VarRef { dest, name } => {
                    values.insert(*dest, name.clone());
                }
                IrInst::Member {
                    object,
                    property,
                    dest,
                } => {
                    let obj = values
                        .get(object)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("{}.{}", obj, property));
                }
                IrInst::MemberComputed {
                    object,
                    property,
                    dest,
                } => {
                    let obj = values
                        .get(object)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let prop = values
                        .get(property)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("{}[{}]", obj, prop));
                }
                IrInst::BinOp { op, lhs, rhs, dest } => {
                    let lhs = values
                        .get(lhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let rhs = values
                        .get(rhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({} {} {})", lhs, self.binop_to_js(*op), rhs));
                }
                IrInst::UnOp { op, arg, dest } => {
                    let arg = values
                        .get(arg)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({}{})", self.unop_to_js(*op), arg));
                }
                IrInst::Call { callee, args, dest } => {
                    let callee = values
                        .get(callee)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let args = args
                        .iter()
                        .map(|a| values.get(a).cloned().unwrap_or_else(|| "undefined".to_string()))
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("{}({})", callee, args));
                }
                IrInst::ArrayLit { dest, elements } => {
                    let parts = elements
                        .iter()
                        .map(|e| {
                            e.and_then(|id| values.get(&id).cloned())
                                .unwrap_or_else(|| "undefined".to_string())
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("[{}]", parts));
                }
                IrInst::LogicalOp { op, lhs, rhs, dest } => {
                    let lhs = values
                        .get(lhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let rhs = values
                        .get(rhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let op_str = match op {
                        argon_ir::LogicOp::And => "&&",
                        argon_ir::LogicOp::Or => "||",
                        argon_ir::LogicOp::Nullish => "??",
                    };
                    values.insert(*dest, format!("({} {} {})", lhs, op_str, rhs));
                }
                IrInst::Conditional {
                    cond,
                    then_value,
                    else_value,
                    dest,
                } => {
                    let cond = values
                        .get(cond)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let then_value = values
                        .get(then_value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let else_value = values
                        .get(else_value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({} ? {} : {})", cond, then_value, else_value));
                }
                IrInst::ThrowStmt { arg } => {
                    let expr =
                        values.get(arg).cloned().unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str(prefix);
                    self.output.push_str("throw ");
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                IrInst::Try {
                    try_body,
                    catch,
                    finally_body,
                } => {
                    self.output.push_str(prefix);
                    self.output.push_str("try {\n");
                    let mut nested_prefix = String::new();
                    nested_prefix.push_str(prefix);
                    nested_prefix.push_str("    ");
                    self.emit_ir_instructions_cfg_with_prefix(
                        try_body,
                        values,
                        &nested_prefix,
                    )?;
                    self.output.push_str(prefix);
                    self.output.push_str("}");

                    if let Some(c) = catch {
                        self.output.push_str(" catch");
                        if let Some(ref p) = c.param {
                            self.output.push_str(" (");
                            self.output.push_str(p);
                            self.output.push_str(")");
                        }
                        self.output.push_str(" {\n");
                        self.emit_ir_instructions_cfg_with_prefix(
                            &c.body,
                            values,
                            &nested_prefix,
                        )?;
                        self.output.push_str(prefix);
                        self.output.push_str("}");
                    }

                    if let Some(f) = finally_body {
                        self.output.push_str(" finally {\n");
                        self.emit_ir_instructions_cfg_with_prefix(
                            f,
                            values,
                            &nested_prefix,
                        )?;
                        self.output.push_str(prefix);
                        self.output.push_str("}");
                    }

                    self.output.push_str("\n");
                }
                IrInst::VarDecl { name, init, .. } => {
                    self.output.push_str(prefix);
                    self.output.push_str("var ");
                    self.output.push_str(name);
                    if let Some(v) = init {
                        let expr =
                            values.get(v).cloned().unwrap_or_else(|| "undefined".to_string());
                        self.output.push_str(" = ");
                        self.output.push_str(&expr);
                    }
                    self.output.push_str(";\n");
                }
                IrInst::AssignVar { name, src } => {
                    let expr =
                        values.get(src).cloned().unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str(prefix);
                    self.output.push_str(name);
                    self.output.push_str(" = ");
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                IrInst::ExprStmt { value } => {
                    let expr = values
                        .get(value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str(prefix);
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                _ => {
                    return Err(CodegenError::Unsupported(format!(
                        "unsupported IR instruction in CFG mode: {:?}",
                        inst
                    )));
                }
            }
        }

        Ok(())
    }

    fn generate_ir_block(
        &mut self,
        block: &argon_ir::BasicBlock,
        is_init: bool,
    ) -> Result<(), CodegenError> {
        use argon_ir::Terminator as IrTerm;

        let mut values: std::collections::HashMap<argon_ir::ValueId, String> =
            std::collections::HashMap::new();

        self.emit_ir_instructions_block_with_prefix(&block.instructions, &mut values, "    ")?;

        if !is_init {
            match &block.terminator {
                IrTerm::Return(Some(v)) => {
                    let expr =
                        values.get(v).cloned().unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str("    return ");
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                IrTerm::Return(None) => {
                    self.output.push_str("    return;\n");
                }
                _ => {
                    return Err(CodegenError::Unsupported(format!(
                        "unsupported IR terminator: {:?}",
                        block.terminator
                    )));
                }
            }
        }

        Ok(())
    }

    fn emit_ir_instructions_block_with_prefix(
        &mut self,
        instructions: &[argon_ir::Instruction],
        values: &mut std::collections::HashMap<argon_ir::ValueId, String>,
        prefix: &str,
    ) -> Result<(), CodegenError> {
        use argon_ir::Instruction as IrInst;

        for inst in instructions {
            match inst {
                IrInst::ObjectLit { dest, props } => {
                    let mut parts = Vec::new();
                    for p in props {
                        let v = values
                            .get(&p.value)
                            .cloned()
                            .unwrap_or_else(|| "undefined".to_string());
                        parts.push(format!("{}: {}", p.key, v));
                    }
                    values.insert(*dest, format!("{{ {} }}", parts.join(", ")));
                }
                IrInst::New { callee, args, dest } => {
                    let callee = values
                        .get(callee)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let args = args
                        .iter()
                        .map(|a| values.get(a).cloned().unwrap_or_else(|| "undefined".to_string()))
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("new {}({})", callee, args));
                }
                IrInst::Await { arg, dest } => {
                    let arg = values
                        .get(arg)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("await {}", arg));
                }
                IrInst::Const { dest, value } => {
                    values.insert(*dest, self.const_to_js(value));
                }
                IrInst::VarRef { dest, name } => {
                    values.insert(*dest, name.clone());
                }
                IrInst::AssignExpr { name, src, dest } => {
                    let expr =
                        values.get(src).cloned().unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({} = {})", name, expr));
                }
                IrInst::ThrowStmt { arg } => {
                    let expr =
                        values.get(arg).cloned().unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str(prefix);
                    self.output.push_str("throw ");
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                IrInst::Try {
                    try_body,
                    catch,
                    finally_body,
                } => {
                    self.output.push_str(prefix);
                    self.output.push_str("try {\n");

                    let mut nested_prefix = String::new();
                    nested_prefix.push_str(prefix);
                    nested_prefix.push_str("    ");
                    self.emit_ir_instructions_block_with_prefix(
                        try_body,
                        values,
                        &nested_prefix,
                    )?;

                    self.output.push_str(prefix);
                    self.output.push_str("}");

                    if let Some(c) = catch {
                        self.output.push_str(" catch");
                        if let Some(ref p) = c.param {
                            self.output.push_str(" (");
                            self.output.push_str(p);
                            self.output.push_str(")");
                        }
                        self.output.push_str(" {\n");
                        self.emit_ir_instructions_block_with_prefix(
                            &c.body,
                            values,
                            &nested_prefix,
                        )?;
                        self.output.push_str(prefix);
                        self.output.push_str("}");
                    }

                    if let Some(f) = finally_body {
                        self.output.push_str(" finally {\n");
                        self.emit_ir_instructions_block_with_prefix(f, values, &nested_prefix)?;
                        self.output.push_str(prefix);
                        self.output.push_str("}");
                    }

                    self.output.push_str("\n");
                }
                IrInst::Member {
                    object,
                    property,
                    dest,
                } => {
                    let obj =
                        values.get(object).cloned().unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("{}.{}", obj, property));
                }
                IrInst::MemberComputed {
                    object,
                    property,
                    dest,
                } => {
                    let obj =
                        values.get(object).cloned().unwrap_or_else(|| "undefined".to_string());
                    let prop = values
                        .get(property)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("{}[{}]", obj, prop));
                }
                IrInst::BinOp { op, lhs, rhs, dest } => {
                    let lhs = values.get(lhs).cloned().unwrap_or_else(|| "undefined".to_string());
                    let rhs = values.get(rhs).cloned().unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({} {} {})", lhs, self.binop_to_js(*op), rhs));
                }
                IrInst::UnOp { op, arg, dest } => {
                    let arg = values.get(arg).cloned().unwrap_or_else(|| "undefined".to_string());
                    values.insert(*dest, format!("({}{})", self.unop_to_js(*op), arg));
                }
                IrInst::Call { callee, args, dest } => {
                    let callee = values
                        .get(callee)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let args = args
                        .iter()
                        .map(|a| values.get(a).cloned().unwrap_or_else(|| "undefined".to_string()))
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("{}({})", callee, args));
                }
                IrInst::ArrayLit { dest, elements } => {
                    let parts = elements
                        .iter()
                        .map(|e| {
                            e.and_then(|id| values.get(&id).cloned())
                                .unwrap_or_else(|| "undefined".to_string())
                        })
                        .collect::<Vec<_>>()
                        .join(", ");
                    values.insert(*dest, format!("[{}]", parts));
                }
                IrInst::LogicalOp { op, lhs, rhs, dest } => {
                    let lhs = values
                        .get(lhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let rhs = values
                        .get(rhs)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let op_str = match op {
                        argon_ir::LogicOp::And => "&&",
                        argon_ir::LogicOp::Or => "||",
                        argon_ir::LogicOp::Nullish => "??",
                    };
                    values.insert(*dest, format!("({} {} {})", lhs, op_str, rhs));
                }
                IrInst::Conditional {
                    cond,
                    then_value,
                    else_value,
                    dest,
                } => {
                    let cond = values
                        .get(cond)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let then_value = values
                        .get(then_value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    let else_value = values
                        .get(else_value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    values.insert(
                        *dest,
                        format!("({} ? {} : {})", cond, then_value, else_value),
                    );
                }
                IrInst::VarDecl { kind, name, init } => {
                    self.output.push_str(prefix);
                    self.output.push_str(match kind {
                        argon_ir::VarKind::Var => "var ",
                        argon_ir::VarKind::Let => "let ",
                        argon_ir::VarKind::Const => "const ",
                    });
                    self.output.push_str(name);
                    if let Some(v) = init {
                        let expr =
                            values.get(v).cloned().unwrap_or_else(|| "undefined".to_string());
                        self.output.push_str(" = ");
                        self.output.push_str(&expr);
                    }
                    self.output.push_str(";\n");
                }
                IrInst::AssignVar { name, src } => {
                    let expr =
                        values.get(src).cloned().unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str(prefix);
                    self.output.push_str(name);
                    self.output.push_str(" = ");
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                IrInst::ExprStmt { value } => {
                    let expr = values
                        .get(value)
                        .cloned()
                        .unwrap_or_else(|| "undefined".to_string());
                    self.output.push_str(prefix);
                    self.output.push_str(&expr);
                    self.output.push_str(";\n");
                }
                // Legacy/control-flow IR is not emitted by the current builder in IR pipeline.
                _ => {
                    return Err(CodegenError::Unsupported(format!(
                        "unsupported IR instruction: {:?}",
                        inst
                    )));
                }
            }
        }

        Ok(())
    }

    fn const_to_js(&self, value: &argon_ir::ConstValue) -> String {
        match value {
            argon_ir::ConstValue::Number(n) => {
                if n.fract() == 0.0 {
                    format!("{}", *n as i64)
                } else {
                    format!("{}", n)
                }
            }
            argon_ir::ConstValue::String(s) => s.clone(),
            argon_ir::ConstValue::Bool(b) => {
                if *b {
                    "true".to_string()
                } else {
                    "false".to_string()
                }
            }
            argon_ir::ConstValue::Null => "null".to_string(),
        }
    }

    fn binop_to_js(&self, op: argon_ir::BinOp) -> &'static str {
        match op {
            argon_ir::BinOp::Add => "+",
            argon_ir::BinOp::Sub => "-",
            argon_ir::BinOp::Mul => "*",
            argon_ir::BinOp::Div => "/",
            argon_ir::BinOp::Mod => "%",
            argon_ir::BinOp::Eq => "===",
            argon_ir::BinOp::Ne => "!==",
            argon_ir::BinOp::Lt => "<",
            argon_ir::BinOp::Le => "<=",
            argon_ir::BinOp::Gt => ">",
            argon_ir::BinOp::Ge => ">=",
            argon_ir::BinOp::And => "&",
            argon_ir::BinOp::Or => "|",
            argon_ir::BinOp::Xor => "^",
            argon_ir::BinOp::Shl => "<<",
            argon_ir::BinOp::Shr => ">>",
            argon_ir::BinOp::Sar => ">>",
        }
    }

    fn unop_to_js(&self, op: argon_ir::UnOp) -> &'static str {
        match op {
            argon_ir::UnOp::Neg => "-",
            argon_ir::UnOp::Not => "!",
        }
    }

    fn generate_statement(&mut self, stmt: &Stmt) -> Result<(), CodegenError> {
        match stmt {
            Stmt::Variable(v) => self.generate_variable(v),
            Stmt::Function(f) => self.generate_function(f),
            Stmt::AsyncFunction(f) => self.generate_async_function(f),
            Stmt::Struct(s) => self.generate_struct(s),
            Stmt::Class(c) => self.generate_class(c),
            Stmt::Expr(e) => {
                self.generate_expression(&e.expr)?;
                self.output.push_str(";\n");
                self.add_line();
                Ok(())
            }
            Stmt::Return(r) => {
                self.output.push_str("return");
                if let Some(ref arg) = r.argument {
                    self.output.push_str(" ");
                    self.generate_expression(arg)?;
                }
                self.output.push_str(";\n");
                self.add_line();
                Ok(())
            }
            Stmt::If(i) => self.generate_if(i),
            Stmt::While(w) => self.generate_while(w),
            Stmt::For(f) => self.generate_for(f),
            Stmt::Block(b) => self.generate_block(b),
            Stmt::Break(_) => {
                self.output.push_str("break;\n");
                self.add_line();
                Ok(())
            }
            Stmt::Continue(_) => {
                self.output.push_str("continue;\n");
                self.add_line();
                Ok(())
            }
            Stmt::Match(m) => self.generate_match(m),
            Stmt::Try(t) => self.generate_try(t),
            Stmt::Throw(t) => self.generate_throw(t),
            Stmt::Switch(s) => self.generate_switch(s),
            Stmt::DoWhile(d) => self.generate_do_while(d),
            Stmt::Import(i) => self.generate_import(i),
            Stmt::Export(e) => self.generate_export(e),
            Stmt::Empty(_) => Ok(()),
            _ => Ok(()),
        }
    }

    fn generate_import(&mut self, import: &argon_ast::ImportStmt) -> Result<(), CodegenError> {
        self.output.push_str("import ");

        for (i, spec) in import.specifiers.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            match spec {
                argon_ast::ImportSpecifier::Default(d) => {
                    self.output.push_str(&d.local.sym);
                }
                argon_ast::ImportSpecifier::Named(n) => {
                    self.output.push_str(&n.imported.sym);
                    if let Some(ref local) = n.local {
                        self.output.push_str(" as ");
                        self.output.push_str(&local.sym);
                    }
                }
                argon_ast::ImportSpecifier::Namespace(n) => {
                    self.output.push_str("* as ");
                    self.output.push_str(&n.id.sym);
                }
            }
        }

        self.output.push_str(" from ");
        self.output.push_str(&import.source.value);
        self.output.push_str(";\n");
        self.add_line();
        Ok(())
    }

    fn generate_export(&mut self, export: &argon_ast::ExportStmt) -> Result<(), CodegenError> {
        self.output.push_str("export ");

        if let Some(ref decl) = export.declaration {
            match decl.as_ref() {
                Stmt::Function(f) => self.generate_function(f)?,
                Stmt::Class(c) => self.generate_class(c)?,
                Stmt::Variable(v) => self.generate_variable(v)?,
                _ => {}
            }
        } else {
            for (i, spec) in export.specifiers.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.output.push_str(&spec.orig.sym);
                if let Some(ref exported) = spec.exported {
                    self.output.push_str(" as ");
                    self.output.push_str(&exported.sym);
                }
            }
        }

        self.output.push_str(";\n");
        self.add_line();
        Ok(())
    }

    fn generate_variable(&mut self, v: &VariableStmt) -> Result<(), CodegenError> {
        self.generate_variable_internal(v, true)
    }

    fn generate_variable_internal(
        &mut self,
        v: &VariableStmt,
        add_semicolon: bool,
    ) -> Result<(), CodegenError> {
        let keyword = match v.kind {
            VariableKind::Var => "var",
            VariableKind::Let => "let",
            VariableKind::Const => "const",
        };

        self.output.push_str(keyword);
        self.output.push_str(" ");

        for (i, decl) in v.declarations.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }

            if let Pattern::Identifier(id) = &decl.id {
                self.output.push_str(&id.name.sym);

                if let Some(ref init) = decl.init {
                    self.output.push_str(" = ");
                    self.generate_expression(init)?;
                }
            }
        }
        if add_semicolon {
            self.output.push_str(";\n");
        }
        Ok(())
    }

    fn generate_function(&mut self, f: &FunctionDecl) -> Result<(), CodegenError> {
        self.output.push_str("function ");
        if let Some(ref id) = f.id {
            self.output.push_str(&id.sym);
        }
        self.output.push_str("(");

        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if let Pattern::Identifier(id) = &p.pat {
                self.output.push_str(&id.name.sym);
            }
        }
        self.output.push_str(") {\n");

        self.indent += 1;
        for stmt in &f.body.statements {
            self.generate_statement(stmt)?;
        }
        self.indent -= 1;

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_struct(&mut self, s: &StructDecl) -> Result<(), CodegenError> {
        // Generate a constructor function for the struct.
        // The parser lowers `Point { x: 1 }` into `new Point({ x: 1 })`,
        // so the constructor expects a single initializer object.
        self.output.push_str("function ");
        self.output.push_str(&s.id.sym);
        self.output.push_str("(init) {\n");

        // Assign fields to this
        for field in &s.fields {
            self.output.push_str("    this.");
            self.output.push_str(&field.id.sym);
            self.output.push_str(" = ");
            self.output.push_str("init.");
            self.output.push_str(&field.id.sym);
            self.output.push_str(";\n");
        }

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_class(&mut self, c: &ClassDecl) -> Result<(), CodegenError> {
        // Generate a constructor function for the class
        self.output.push_str("function ");
        self.output.push_str(&c.id.sym);
        self.output.push_str("(");

        // Find constructor and get its params
        let mut has_constructor = false;
        for member in &c.body.body {
            if let ClassMember::Constructor(constr) = member {
                has_constructor = true;
                let params: Vec<_> = constr
                    .params
                    .iter()
                    .map(|p| {
                        if let Pattern::Identifier(id) = &p.pat {
                            id.name.sym.as_str()
                        } else {
                            ""
                        }
                    })
                    .collect();
                self.output.push_str(&params.join(", "));
            }
        }

        if !has_constructor {
            self.output.push_str(")");
        }

        self.output.push_str(") {\n");

        // Generate constructor body
        for member in &c.body.body {
            match member {
                ClassMember::Constructor(constr) => {
                    for stmt in &constr.body.statements {
                        self.generate_statement(stmt)?;
                    }
                }
                ClassMember::Field(field) => {
                    // Generate field initialization if there's a value
                    if let Some(value) = &field.value {
                        self.output.push_str("this.");
                        self.generate_expression(&field.key)?;
                        self.output.push_str(" = ");
                        self.generate_expression(value)?;
                        self.output.push_str(";\n");
                    }
                }
                ClassMember::Method(method) => {
                    // Generate method
                    self.output.push_str("this.");
                    self.generate_expression(&method.key)?;
                    self.output.push_str(" = function(");

                    // Method params
                    let params: Vec<_> = method
                        .value
                        .params
                        .iter()
                        .map(|p| {
                            if let Pattern::Identifier(id) = &p.pat {
                                id.name.sym.as_str()
                            } else {
                                ""
                            }
                        })
                        .collect();
                    self.output.push_str(&params.join(", "));
                    self.output.push_str(") {\n");

                    // Method body
                    for stmt in &method.value.body.statements {
                        self.generate_statement(stmt)?;
                    }

                    self.output.push_str("};\n");
                }
                _ => {
                    // Other class members not supported yet
                }
            }
        }

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_expression(&mut self, expr: &Expr) -> Result<(), CodegenError> {
        match expr {
            Expr::Literal(lit) => self.generate_literal(lit),
            Expr::Identifier(id) => {
                self.output.push_str(&id.sym);
                Ok(())
            }
            Expr::Binary(b) => self.generate_binary(b),
            Expr::Unary(u) => self.generate_unary(u),
            Expr::Call(c) => self.generate_call(c),
            Expr::Member(m) => self.generate_member(m),
            Expr::Assignment(a) => self.generate_assignment(a),
            Expr::This(_) => {
                self.output.push_str("this");
                Ok(())
            }
            Expr::Await(a) => {
                self.output.push_str("await ");
                self.generate_expression(&a.argument)?;
                Ok(())
            }
            Expr::New(n) => {
                self.output.push_str("new ");
                self.generate_expression(&n.callee)?;
                self.output.push_str("(");
                for arg in &n.arguments {
                    if let ExprOrSpread::Expr(e) = arg {
                        self.generate_expression(e)?;
                    }
                }
                self.output.push_str(")");
                Ok(())
            }
            Expr::Conditional(c) => {
                self.output.push_str("(");
                self.generate_expression(&c.test)?;
                self.output.push_str(" ? ");
                self.generate_expression(&c.consequent)?;
                self.output.push_str(" : ");
                self.generate_expression(&c.alternate)?;
                self.output.push_str(")");
                Ok(())
            }
            Expr::Object(o) => self.generate_object(o),
            Expr::Ref(r) => {
                self.generate_expression(&r.expr)?;
                Ok(())
            }
            Expr::MutRef(r) => {
                self.generate_expression(&r.expr)?;
                Ok(())
            }
            Expr::JsxElement(e) => self.generate_jsx_element(e),
            Expr::JsxFragment(f) => self.generate_jsx_fragment(f),
            _ => {
                self.output.push_str("undefined");
                Ok(())
            }
        }
    }

    fn generate_literal(&mut self, lit: &Literal) -> Result<(), CodegenError> {
        match lit {
            Literal::Number(n) => {
                self.output.push_str(&n.raw);
                Ok(())
            }
            Literal::String(s) => {
                self.output.push_str(&s.value);
                Ok(())
            }
            Literal::Boolean(b) => {
                self.output.push_str(if b.value { "true" } else { "false" });
                Ok(())
            }
            Literal::Null(_) => {
                self.output.push_str("null");
                Ok(())
            }
            _ => Ok(()),
        }
    }

    fn generate_binary(&mut self, b: &BinaryExpr) -> Result<(), CodegenError> {
        self.output.push_str("(");
        self.generate_expression(&b.left)?;

        let op = match b.operator {
            BinaryOperator::Plus => "+",
            BinaryOperator::Minus => "-",
            BinaryOperator::Multiply => "*",
            BinaryOperator::Divide => "/",
            BinaryOperator::Modulo => "%",
            BinaryOperator::Equal => "===",
            BinaryOperator::NotEqual => "!==",
            BinaryOperator::StrictEqual => "===",
            BinaryOperator::StrictNotEqual => "!==",
            BinaryOperator::LessThan => "<",
            BinaryOperator::LessThanOrEqual => "<=",
            BinaryOperator::GreaterThan => ">",
            BinaryOperator::GreaterThanOrEqual => ">=",
            BinaryOperator::BitwiseAnd => "&",
            BinaryOperator::BitwiseOr => "|",
            BinaryOperator::BitwiseXor => "^",
            BinaryOperator::LeftShift => "<<",
            BinaryOperator::RightShift => ">>",
            _ => " + ",
        };

        self.output.push_str(&format!(" {} ", op));
        self.generate_expression(&b.right)?;
        self.output.push_str(")");
        Ok(())
    }

    fn generate_unary(&mut self, u: &UnaryExpr) -> Result<(), CodegenError> {
        let op = match u.operator {
            UnaryOperator::Minus => "-",
            UnaryOperator::Plus => "+",
            UnaryOperator::LogicalNot => "!",
            UnaryOperator::BitwiseNot => "~",
            UnaryOperator::Typeof => "typeof ",
            _ => "",
        };
        self.output.push_str(op);
        self.generate_expression(&u.argument)?;
        Ok(())
    }

    fn generate_jsx_element(&mut self, elem: &JsxElement) -> Result<(), CodegenError> {
        self.output.push_str("React.createElement(");

        // Generate element name
        self.generate_jsx_element_name(&elem.opening.name)?;

        // Build attributes object
        if !elem.opening.attributes.is_empty() {
            self.output.push_str(", { ");
            for (i, attr) in elem.opening.attributes.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.generate_jsx_attribute(attr)?;
            }
            self.output.push_str(" }");
        } else {
            self.output.push_str(", null");
        }

        // Build children
        if elem.children.is_empty() {
            self.output.push_str(", null");
        } else {
            self.output.push_str(", ");
            for (i, child) in elem.children.iter().enumerate() {
                if i > 0 {
                    self.output.push_str(", ");
                }
                self.generate_jsx_child(child)?;
            }
        }

        self.output.push_str(")");
        Ok(())
    }

    fn generate_jsx_fragment(&mut self, frag: &JsxFragment) -> Result<(), CodegenError> {
        self.output
            .push_str("React.createElement(React.Fragment, null, ");
        for (i, child) in frag.children.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            self.generate_jsx_child(child)?;
        }
        self.output.push_str(")");
        Ok(())
    }

    fn generate_jsx_element_name(&mut self, name: &JsxElementName) -> Result<(), CodegenError> {
        match name {
            JsxElementName::Identifier(id) => {
                self.output.push_str(&format!("\"{}\"", id.sym));
            }
            JsxElementName::Namespaced(ns) => {
                self.output
                    .push_str(&format!("\"{}:{}\"", ns.namespace.sym, ns.name.sym));
            }
            JsxElementName::Member(m) => {
                self.generate_jsx_member_name(m)?;
            }
        }
        Ok(())
    }

    fn generate_jsx_member_name(&mut self, name: &JsxElementName) -> Result<(), CodegenError> {
        match name {
            JsxElementName::Identifier(id) => {
                self.output.push_str(&format!("\"{}\"", id.sym));
            }
            JsxElementName::Member(m) => {
                self.generate_jsx_member_name(m)?;
                if let JsxElementName::Identifier(id) = m.as_ref() {
                    self.output.push_str(&format!(".{}", id.sym));
                }
            }
            _ => {}
        }
        Ok(())
    }

    fn generate_jsx_attribute(&mut self, attr: &JsxAttribute) -> Result<(), CodegenError> {
        let name = match &attr.name {
            JsxAttributeName::Identifier(id) => &id.sym,
            JsxAttributeName::Namespaced(ns) => &format!("{}:{}", ns.namespace.sym, ns.name.sym),
        };

        if let Some(value) = &attr.value {
            match value {
                JsxAttributeValue::String(s) => {
                    self.output.push_str(&format!("{}: \"{}\"", name, s.value));
                }
                JsxAttributeValue::Expression(e) => {
                    self.output.push_str(name);
                    self.output.push_str(": (");
                    self.generate_expression(e)?;
                    self.output.push_str(")");
                }
                JsxAttributeValue::Element(_) | JsxAttributeValue::Fragment(_) => {
                    self.output.push_str(name);
                    self.output.push_str(": ");
                    // Handle nested elements
                }
                JsxAttributeValue::Span(_) => {}
            }
        } else {
            // Boolean attribute
            self.output.push_str(&format!("{}: true", name));
        }
        Ok(())
    }

    fn generate_jsx_child(&mut self, child: &JsxChild) -> Result<(), CodegenError> {
        match child {
            JsxChild::Text(t) => {
                self.output
                    .push_str(&format!("\"{}\"", t.value.replace("\"", "\\\"")));
            }
            JsxChild::Expression(e) => {
                self.generate_expression(e)?;
            }
            JsxChild::Element(e) => {
                self.output.push_str("React.createElement(");
                self.generate_jsx_element(e)?;
                self.output.push_str(")");
            }
            JsxChild::Fragment(f) => {
                self.output.push_str("React.Fragment(null, [");
                for (i, child) in f.children.iter().enumerate() {
                    if i > 0 {
                        self.output.push_str(", ");
                    }
                    self.generate_jsx_child(child)?;
                }
                self.output.push_str("])");
            }
            JsxChild::Spread(s) => {
                self.output.push_str("...");
                self.generate_expression(&s.expression)?;
            }
        }
        Ok(())
    }

    fn generate_call(&mut self, c: &CallExpr) -> Result<(), CodegenError> {
        // Check if this is a Some(), None, Ok(), or Err() call
        if let Expr::Identifier(id) = c.callee.as_ref() {
            match id.sym.as_str() {
                "Some" => {
                    self.output.push_str("new Argon.Option.Some(");
                    for (i, arg) in c.arguments.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        if let ExprOrSpread::Expr(e) = arg {
                            self.generate_expression(e)?;
                        }
                    }
                    self.output.push_str(")");
                    return Ok(());
                }
                "None" => {
                    self.output.push_str("new Argon.Option.None()");
                    return Ok(());
                }
                "Ok" => {
                    self.output.push_str("new Argon.Result.Ok(");
                    for (i, arg) in c.arguments.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        if let ExprOrSpread::Expr(e) = arg {
                            self.generate_expression(e)?;
                        }
                    }
                    self.output.push_str(")");
                    return Ok(());
                }
                "Err" => {
                    self.output.push_str("new Argon.Result.Err(");
                    for (i, arg) in c.arguments.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        if let ExprOrSpread::Expr(e) = arg {
                            self.generate_expression(e)?;
                        }
                    }
                    self.output.push_str(")");
                    return Ok(());
                }
                "Vec" => {
                    self.output.push_str("new Argon.Vec(");
                    for (i, arg) in c.arguments.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        if let ExprOrSpread::Expr(e) = arg {
                            self.generate_expression(e)?;
                        }
                    }
                    self.output.push_str(")");
                    return Ok(());
                }
                "Shared" => {
                    self.output.push_str("Argon.Shared.wrap(");
                    for (i, arg) in c.arguments.iter().enumerate() {
                        if i > 0 {
                            self.output.push_str(", ");
                        }
                        if let ExprOrSpread::Expr(e) = arg {
                            self.generate_expression(e)?;
                        }
                    }
                    self.output.push_str(")");
                    return Ok(());
                }
                _ => {}
            }
        }

        // Check if this is a Argon.Option.Some, Argon.Result.Ok, etc. call
        if let Expr::Member(m) = c.callee.as_ref() {
            if let Expr::Member(outer) = m.object.as_ref() {
                if let Expr::Identifier(obj_id) = outer.object.as_ref() {
                    if obj_id.sym == "Argon" {
                        if let Expr::Identifier(inner_id) = outer.property.as_ref() {
                            if let Expr::Identifier(method_id) = m.property.as_ref() {
                                // Check for Option.Some, Option.None, Result.Ok, Result.Err
                                if inner_id.sym == "Option" {
                                    match method_id.sym.as_str() {
                                        "Some" => {
                                            self.output.push_str("new Argon.Option.Some(");
                                            for (i, arg) in c.arguments.iter().enumerate() {
                                                if i > 0 {
                                                    self.output.push_str(", ");
                                                }
                                                if let ExprOrSpread::Expr(e) = arg {
                                                    self.generate_expression(e)?;
                                                }
                                            }
                                            self.output.push_str(")");
                                            return Ok(());
                                        }
                                        "None" => {
                                            self.output.push_str("new Argon.Option.None()");
                                            return Ok(());
                                        }
                                        _ => {}
                                    }
                                }
                                if inner_id.sym == "Result" {
                                    match method_id.sym.as_str() {
                                        "Ok" => {
                                            self.output.push_str("new Argon.Result.Ok(");
                                            for (i, arg) in c.arguments.iter().enumerate() {
                                                if i > 0 {
                                                    self.output.push_str(", ");
                                                }
                                                if let ExprOrSpread::Expr(e) = arg {
                                                    self.generate_expression(e)?;
                                                }
                                            }
                                            self.output.push_str(")");
                                            return Ok(());
                                        }
                                        "Err" => {
                                            self.output.push_str("new Argon.Result.Err(");
                                            for (i, arg) in c.arguments.iter().enumerate() {
                                                if i > 0 {
                                                    self.output.push_str(", ");
                                                }
                                                if let ExprOrSpread::Expr(e) = arg {
                                                    self.generate_expression(e)?;
                                                }
                                            }
                                            self.output.push_str(")");
                                            return Ok(());
                                        }
                                        _ => {}
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }

        self.generate_expression(&c.callee)?;
        self.output.push_str("(");
        for (i, arg) in c.arguments.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if let ExprOrSpread::Expr(e) = arg {
                self.generate_expression(e)?;
            }
        }
        self.output.push_str(")");
        Ok(())
    }

    fn generate_object(&mut self, o: &ObjectExpression) -> Result<(), CodegenError> {
        self.output.push_str("{ ");
        for (i, prop) in o.properties.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            match prop {
                ObjectProperty::Property(p) => {
                    self.generate_expression(&p.key)?;
                    self.output.push_str(": ");
                    if let ExprOrSpread::Expr(e) = &p.value {
                        self.generate_expression(e)?;
                    }
                }
                ObjectProperty::Shorthand(id) => {
                    self.output.push_str(&id.sym);
                }
                _ => {}
            }
        }
        self.output.push_str(" }");
        Ok(())
    }

    fn generate_member(&mut self, m: &MemberExpr) -> Result<(), CodegenError> {
        self.generate_expression(&m.object)?;

        if m.computed {
            self.output.push_str("[");
            self.generate_expression(&m.property)?;
            self.output.push_str("]");
        } else {
            self.output.push_str(".");
            self.generate_expression(&m.property)?;
        }
        Ok(())
    }

    fn generate_assignment(&mut self, a: &AssignmentExpr) -> Result<(), CodegenError> {
        self.generate_assignment_target(&a.left)?;

        let op = match a.operator {
            AssignmentOperator::Assign => "=",
            AssignmentOperator::PlusAssign => "+=",
            AssignmentOperator::MinusAssign => "-=",
            AssignmentOperator::MultiplyAssign => "*=",
            AssignmentOperator::DivideAssign => "/=",
            _ => "=",
        };

        self.output.push_str(&format!(" {} ", op));
        self.generate_expression(&a.right)?;
        Ok(())
    }

    fn generate_assignment_target(
        &mut self,
        target: &AssignmentTarget,
    ) -> Result<(), CodegenError> {
        match target {
            AssignmentTarget::Simple(expr) => {
                self.generate_expression(expr)?;
            }
            AssignmentTarget::Member(member) => {
                self.generate_expression(&member.object)?;
                self.output.push_str(".");
                self.generate_expression(&member.property)?;
            }
            _ => {
                self.output.push_str("/* target */");
            }
        }
        Ok(())
    }

    fn generate_if(&mut self, i: &IfStmt) -> Result<(), CodegenError> {
        self.output.push_str("if (");
        self.generate_expression(&i.condition)?;
        self.output.push_str(") {\n");

        self.indent += 1;
        self.generate_statement(&i.consequent)?;
        self.indent -= 1;

        if let Some(ref alt) = i.alternate {
            self.output.push_str("} else {\n");
            self.indent += 1;
            self.generate_statement(alt)?;
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_while(&mut self, w: &WhileStmt) -> Result<(), CodegenError> {
        self.output.push_str("while (");
        self.generate_expression(&w.condition)?;
        self.output.push_str(") {\n");

        self.indent += 1;
        self.generate_statement(&w.body)?;
        self.indent -= 1;

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_for(&mut self, f: &ForStmt) -> Result<(), CodegenError> {
        self.output.push_str("for (");

        if let Some(ref init) = f.init {
            match init {
                ForInit::Variable(v) => self.generate_variable_internal(v, false)?,
                ForInit::Expr(e) => self.generate_expression(e)?,
            }
        }

        self.output.push_str(";");

        if let Some(ref test) = f.test {
            self.output.push_str(" ");
            self.generate_expression(test)?;
        }

        if f.update.is_some() {
            self.output.push_str("; ");
            self.generate_expression(f.update.as_ref().unwrap())?;
        }

        self.output.push_str(") ");

        // Generate body
        match &*f.body {
            Stmt::Block(b) => {
                self.output.push_str("{\n");
                self.indent += 1;
                for stmt in &b.statements {
                    self.generate_statement(stmt)?;
                }
                self.indent -= 1;
                self.output.push_str("}\n");
            }
            _ => {
                self.output.push_str("{\n");
                self.indent += 1;
                self.generate_statement(&f.body)?;
                self.indent -= 1;
                self.output.push_str("}\n");
            }
        }
        Ok(())
    }

    fn generate_block(&mut self, b: &BlockStmt) -> Result<(), CodegenError> {
        self.output.push_str("{\n");
        self.indent += 1;

        for stmt in &b.statements {
            self.generate_statement(stmt)?;
        }

        self.indent -= 1;
        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_match(&mut self, m: &MatchStmt) -> Result<(), CodegenError> {
        // Check if this is an Option or Result match pattern
        let type_name = self.detect_option_result_type(&m.discriminant);

        if let Some(type_name) = type_name {
            let patterns: Vec<(String, &MatchCase)> = m
                .cases
                .iter()
                .filter_map(|case| {
                    if let Expr::Member(m) = &case.pattern {
                        if let Expr::Identifier(method_id) = m.property.as_ref() {
                            return Some((method_id.sym.clone(), case));
                        }
                    }
                    None
                })
                .collect();

            if !patterns.is_empty() {
                return self.generate_option_result_match(&type_name, &m.discriminant, &patterns);
            }
        }

        // Default switch-based match for other types
        self.output.push_str("switch (");
        self.generate_expression(&m.discriminant)?;
        self.output.push_str(") {\n");

        for case in &m.cases {
            self.output.push_str("case ");
            self.generate_expression(&case.pattern)?;
            self.output.push_str(":\n");

            self.indent += 1;
            self.generate_statement(case.consequent.as_ref())?;
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn detect_option_result_type(&self, discriminant: &Expr) -> Option<String> {
        // Check if discriminant is accessing isSome/isNone or isOk/isErr
        let type_name = match discriminant {
            Expr::Member(m) => {
                let obj = &m.object;
                if let Expr::Identifier(_) = obj.as_ref() {
                    if let Expr::Identifier(method_id) = m.property.as_ref() {
                        match method_id.sym.as_str() {
                            "isSome" | "isNone" => Some("Option".to_string()),
                            "isOk" | "isErr" => Some("Result".to_string()),
                            _ => None,
                        }
                    } else {
                        None
                    }
                } else {
                    None
                }
            }
            _ => None,
        };
        type_name
    }

    fn generate_option_result_match(
        &mut self,
        type_name: &str,
        discriminant: &Expr,
        patterns: &[(String, &MatchCase)],
    ) -> Result<(), CodegenError> {
        // Generate if-else chain for Option/Result pattern matching
        // discriminant.isSome() ? discriminant.unwrap() : default

        let method_true = if type_name == "Option" {
            "isSome"
        } else {
            "isOk"
        };

        for (i, (method, case)) in patterns.iter().enumerate() {
            if i == 0 {
                self.output.push_str("if (");
                self.generate_expression(discriminant)?;
                self.output.push_str(&format!(".{}()) {{\n", method_true));
            } else {
                self.output.push_str("} else if (");
                self.generate_expression(discriminant)?;
                self.output.push_str(&format!(".{}()) {{\n", method));
            }

            self.indent += 1;
            self.generate_statement(case.consequent.as_ref())?;
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_async_function(&mut self, f: &FunctionDecl) -> Result<(), CodegenError> {
        self.output.push_str("async function ");
        if let Some(ref id) = f.id {
            self.output.push_str(&id.sym);
        }
        self.output.push_str("(");

        for (i, p) in f.params.iter().enumerate() {
            if i > 0 {
                self.output.push_str(", ");
            }
            if let Pattern::Identifier(id) = &p.pat {
                self.output.push_str(&id.name.sym);
            }
        }
        self.output.push_str(") {\n");

        self.indent += 1;
        for stmt in &f.body.statements {
            self.generate_statement(stmt)?;
        }
        self.indent -= 1;

        self.output.push_str("}\n\n");
        Ok(())
    }

    fn generate_try(&mut self, t: &TryStmt) -> Result<(), CodegenError> {
        self.output.push_str("try {\n");
        self.indent += 1;
        for stmt in &t.block.statements {
            self.generate_statement(stmt)?;
        }
        self.indent -= 1;

        if let Some(ref handler) = t.handler {
            self.output.push_str("} catch ");
            if let Some(ref param) = handler.param {
                self.output.push_str("(");
                if let Pattern::Identifier(id) = param {
                    self.output.push_str(&id.name.sym);
                }
                self.output.push_str(") ");
            }
            self.output.push_str("{\n");
            self.indent += 1;
            for stmt in &handler.body.statements {
                self.generate_statement(stmt)?;
            }
            self.indent -= 1;
        }

        if let Some(ref finalizer) = t.finalizer {
            self.output.push_str("} finally {\n");
            self.indent += 1;
            for stmt in &finalizer.statements {
                self.generate_statement(stmt)?;
            }
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_throw(&mut self, t: &ThrowStmt) -> Result<(), CodegenError> {
        self.output.push_str("throw ");
        self.generate_expression(&t.argument)?;
        self.output.push_str(";\n");
        Ok(())
    }

    fn generate_switch(&mut self, s: &SwitchStmt) -> Result<(), CodegenError> {
        self.output.push_str("switch (");
        self.generate_expression(&s.discriminant)?;
        self.output.push_str(") {\n");

        for case in &s.cases {
            if let Some(ref test) = case.test {
                self.output.push_str("case ");
                self.generate_expression(test)?;
                self.output.push_str(":\n");
            } else {
                self.output.push_str("default:\n");
            }

            self.indent += 1;
            for stmt in &case.consequent {
                self.generate_statement(stmt)?;
            }
            self.indent -= 1;
        }

        self.output.push_str("}\n");
        Ok(())
    }

    fn generate_do_while(&mut self, d: &DoWhileStmt) -> Result<(), CodegenError> {
        self.output.push_str("do {\n");
        self.indent += 1;
        self.generate_statement(&d.body)?;
        self.indent -= 1;
        self.output.push_str("} while (");
        self.generate_expression(&d.condition)?;
        self.output.push_str(");\n");
        Ok(())
    }

    #[allow(dead_code)]
    fn indent(&mut self) {
        for _ in 0..self.indent {
            self.output.push_str("    ");
        }
    }
}

#[derive(Debug)]
pub enum CodegenError {
    Unsupported(String),
}

impl std::fmt::Display for CodegenError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            CodegenError::Unsupported(msg) => write!(f, "Unsupported: {}", msg),
        }
    }
}

impl std::error::Error for CodegenError {}

pub fn generate_type_declarations(source: &SourceFile) -> String {
    let mut output = String::new();
    output.push_str("// TypeScript declarations generated by Argon\n\n");

    for stmt in &source.statements {
        match stmt {
            Stmt::Function(f) => {
                output.push_str("declare function ");
                if let Some(ref id) = f.id {
                    output.push_str(&id.sym);
                }
                output.push('(');
                for (i, p) in f.params.iter().enumerate() {
                    if i > 0 {
                        output.push_str(", ");
                    }
                    if let Pattern::Identifier(id) = &p.pat {
                        output.push_str(&id.name.sym);
                        if let Some(ref ty) = p.ty {
                            output.push_str(": ");
                            output.push_str(&type_to_ts_string(ty));
                        }
                    }
                }
                output.push(')');
                if let Some(ref ret_ty) = f.return_type {
                    output.push_str(": ");
                    output.push_str(&type_to_ts_string(ret_ty));
                }
                output.push_str(";\n\n");
            }
            Stmt::Struct(s) => {
                output.push_str("interface ");
                output.push_str(&s.id.sym);
                output.push_str(" {\n");
                for field in &s.fields {
                    output.push_str("    ");
                    output.push_str(&field.id.sym);
                    output.push_str(": ");
                    output.push_str(&type_to_ts_string(&field.type_annotation));
                    output.push_str(";\n");
                }
                output.push_str("}\n\n");
            }
            Stmt::Class(c) => {
                output.push_str("class ");
                output.push_str(&c.id.sym);
                output.push_str(" {\n");
                for member in &c.body.body {
                    match member {
                        ClassMember::Field(f) => {
                            output.push_str("    ");
                            if let Expr::Identifier(id) = &f.key {
                                output.push_str(&id.sym);
                            }
                            if let Some(ref ty) = f.type_annotation {
                                output.push_str(": ");
                                output.push_str(&type_to_ts_string(ty));
                            }
                            output.push_str(";\n");
                        }
                        ClassMember::Method(m) => {
                            output.push_str("    ");
                            if let Expr::Identifier(id) = &m.key {
                                output.push_str(&id.sym);
                            }
                            output.push('(');
                            for (i, p) in m.value.params.iter().enumerate() {
                                if i > 0 {
                                    output.push_str(", ");
                                }
                                if let Pattern::Identifier(id) = &p.pat {
                                    output.push_str(&id.name.sym);
                                }
                            }
                            output.push(')');
                            if let Some(ref ret_ty) = m.value.return_type {
                                output.push_str(": ");
                                output.push_str(&type_to_ts_string(ret_ty));
                            }
                            output.push_str(";\n");
                        }
                        _ => {}
                    }
                }
                output.push_str("}\n\n");
            }
            Stmt::Interface(i) => {
                output.push_str("interface ");
                output.push_str(&i.id.sym);
                output.push_str(" {\n");
                for member in &i.body.body {
                    match member {
                        InterfaceMember::Method(m) => {
                            output.push_str("    ");
                            output.push_str(&m.id.sym);
                            output.push('(');
                            for (i, p) in m.params.iter().enumerate() {
                                if i > 0 {
                                    output.push_str(", ");
                                }
                                if let Pattern::Identifier(id) = &p.pat {
                                    output.push_str(&id.name.sym);
                                }
                            }
                            output.push(')');
                            if let Some(ref ret_ty) = m.return_type {
                                output.push_str(": ");
                                output.push_str(&type_to_ts_string(ret_ty));
                            }
                            output.push_str(";\n");
                        }
                        InterfaceMember::Property(p) => {
                            output.push_str("    ");
                            output.push_str(&p.id.sym);
                            if p.is_optional {
                                output.push('?');
                            }
                            output.push_str(": ");
                            if let Some(ref ty) = p.type_annotation {
                                output.push_str(&type_to_ts_string(ty));
                            }
                            output.push_str(";\n");
                        }
                        InterfaceMember::IndexSignature(_) => {}
                    }
                }
                output.push_str("}\n\n");
            }
            Stmt::TypeAlias(t) => {
                output.push_str("type ");
                output.push_str(&t.id.sym);
                output.push_str(" = ");
                output.push_str(&type_to_ts_string(&t.type_annotation));
                output.push_str(";\n\n");
            }
            Stmt::Enum(e) => {
                output.push_str("enum ");
                output.push_str(&e.id.sym);
                output.push_str(" {\n");
                for (i, member) in e.members.iter().enumerate() {
                    output.push_str("    ");
                    output.push_str(&member.id.sym);
                    if i < e.members.len() - 1 {
                        output.push(',');
                    }
                    output.push('\n');
                }
                output.push_str("}\n\n");
            }
            _ => {}
        }
    }

    output
}

fn type_to_ts_string(ty: &argon_ast::Type) -> String {
    match ty {
        argon_ast::Type::Primitive(p) => match p {
            PrimitiveType::Number => "number".to_string(),
            PrimitiveType::String => "string".to_string(),
            PrimitiveType::Boolean => "boolean".to_string(),
            PrimitiveType::Void => "void".to_string(),
            PrimitiveType::Null => "null".to_string(),
            PrimitiveType::Undefined => "undefined".to_string(),
            PrimitiveType::Any => "any".to_string(),
            PrimitiveType::Unknown => "unknown".to_string(),
            PrimitiveType::Never => "never".to_string(),
            _ => "any".to_string(),
        },
        argon_ast::Type::Reference(r) => {
            if let TypeName::Ident(id) = &r.name {
                if r.type_args.is_empty() {
                    id.sym.clone()
                } else {
                    let args: Vec<String> =
                        r.type_args.iter().map(|t| type_to_ts_string(t)).collect();
                    format!("{}<{}>", id.sym, args.join(", "))
                }
            } else {
                "any".to_string()
            }
        }
        argon_ast::Type::Array(arr) => {
            format!("{}[]", type_to_ts_string(&arr.elem_type))
        }
        argon_ast::Type::Ref(r) => type_to_ts_string(&r.ty),
        argon_ast::Type::MutRef(r) => type_to_ts_string(&r.ty),
        argon_ast::Type::Function(f) => {
            let params: Vec<String> = f.params.iter().map(|p| type_to_ts_string(&p.ty)).collect();
            format!(
                "({}) => {}",
                params.join(", "),
                type_to_ts_string(&f.return_type)
            )
        }
        argon_ast::Type::Union(u) => {
            let types: Vec<String> = u.types.iter().map(|t| type_to_ts_string(t)).collect();
            types.join(" | ")
        }
        argon_ast::Type::Intersection(i) => {
            let types: Vec<String> = i.types.iter().map(|t| type_to_ts_string(t)).collect();
            types.join(" & ")
        }
        _ => "any".to_string(),
    }
}

#[cfg(test)]
mod codegen_tests;
