//! Argon CLI Integration Tests

use assert_cmd::cargo::cargo_bin_cmd;
use predicates::prelude::*;
use std::fs;
use std::path::PathBuf;

#[allow(dead_code)]
fn test_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

#[test]
fn test_compile_simple() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("test.arg");
    fs::write(&source_file, "const x = 5;\nconsole.log(x);\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success()
        .stdout(predicate::str::contains("Parsing"))
        .stdout(predicate::str::contains("Type checking"))
        .stdout(predicate::str::contains("Borrow checking"))
        .stdout(predicate::str::contains("Generating JavaScript"))
        .stdout(predicate::str::contains("Done"));

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("Generated by Argon (IR)"));
    assert!(output.contains("const x = 5"));
    assert!(output.contains("console.log(x)"));
}

#[test]
fn test_compile_writes_source_map_when_enabled() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("sourcemap.arg");
    fs::write(&source_file, "const x = 5;\nconsole.log(x);\n").unwrap();

    let output_js = temp_dir.path().join("output.js");
    let output_map = temp_dir.path().join("output.js.map");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_js)
        .arg("--pipeline")
        .arg("ir")
        .arg("--source-map")
        .assert()
        .success();

    let js = fs::read_to_string(&output_js).unwrap();
    assert!(js.contains("sourceMappingURL=output.js.map"));

    let map = fs::read_to_string(&output_map).unwrap();
    assert!(map.contains("\"version\":3"));
}

#[test]
fn test_compile_logical_conditional_array_and_assignment() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("exprs.arg");
    fs::write(
        &source_file,
        "function f(a: i32, b: i32): i32 {\n    let x = 0;\n    x = a > b ? a : b;\n    const ok = (a > 0) && (b > 0);\n    const arr = [1, 2, 3];\n    if (ok) { return x + arr[0]; }\n    return x;\n}\nconsole.log(f(1, 2));\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("[1, 2, 3]"));
    assert!(output.contains("&&"));
    assert!(output.contains("?"));
    assert!(output.contains("x ="));
    assert!(output.contains("arr[0]"));
}

#[test]
fn test_compile_function() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("function.arg");
    fs::write(
        &source_file,
        "function add(a: number, b: number): number {\n    return a + b;\n}\nconsole.log(add(1, 2));\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("function add"));
}

#[test]
fn test_compile_struct() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("struct.arg");
    fs::write(
        &source_file,
        "struct Point {\n    x: number;\n    y: number;\n}\nconst p = Point { x: 1, y: 2 };\nconsole.log(p.x);\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("function Point(init)"));
    assert!(output.contains("this.x = init.x"));
    assert!(output.contains("this.y = init.y"));
    assert!(output.contains("new Point({ x: 1, y: 2 })"));
}

#[test]
fn test_check_validates_borrow_checker() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("borrow.arg");
    // This should compile successfully with borrow checking
    fs::write(
        &source_file,
        "function test(x: number): void {\n    const y = x;\n}\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("check").arg(&source_file).assert().success();
}

#[test]
fn test_compile_with_declarations() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("decl.arg");
    fs::write(
        &source_file,
        "function greet(name: string): string {\n    return \"Hello, \" + name;\n}\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--declarations")
        .assert()
        .success();

    let dts = fs::read_to_string(temp_dir.path().join("output.d.ts")).unwrap();
    assert!(dts.contains("greet"));
}

#[test]
fn test_invalid_syntax_fails() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("invalid.arg");
    fs::write(&source_file, "const x = ;\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .assert()
        .failure();
}

#[test]
fn test_help_output() {
    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains("Argon"));
}

#[test]
fn test_compile_async_and_await() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("async.arg");
    fs::write(
        &source_file,
        "async function greet(): string {\n    return \"hello\";\n}\nasync function main(): string {\n    const result = await greet();\n    return result;\n}\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("async function greet"));
    assert!(output.contains("async function main"));
    assert!(output.contains("await greet()"));
}

#[test]
fn test_compile_jsx() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("jsx.arg");
    fs::write(&source_file, "<div className=\"test\">Hello</div>\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("React.createElement"));
    assert!(output.contains("\"div\""));
    assert!(output.contains("className"));
    assert!(output.contains("\"Hello\""));
}

#[test]
fn test_compile_example_control_flow_uses_cfg_in_ir() {
    let temp_dir = tempfile::tempdir().unwrap();
    let example = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("examples")
        .join("control-flow.arg");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&example)
        .arg("--pipeline")
        .arg("ir")
        .arg("-o")
        .arg(temp_dir.path().join("out.js"))
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("out.js")).unwrap();
    // The IR CFG emitter uses a bb state machine.
    assert!(output.contains("switch (__bb)"));
    assert!(output.contains("console.log(i)"));
}

#[test]
fn test_compile_example_esm_import() {
    let temp_dir = tempfile::tempdir().unwrap();
    let example = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("examples")
        .join("esm.arg");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&example)
        .arg("--pipeline")
        .arg("ir")
        .arg("-o")
        .arg(temp_dir.path().join("out.js"))
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("out.js")).unwrap();
    assert!(output.contains("import y from \"test\";"));
    assert!(output.contains("const x = 1"));
}
