//! Argon CLI Integration Tests

use assert_cmd::cargo::cargo_bin_cmd;
use predicates::prelude::*;
use std::fs;
use std::path::PathBuf;
use std::process::Command;

#[allow(dead_code)]
fn test_dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
}

fn repo_root() -> PathBuf {
    test_dir().join("..").join("..")
}

fn examples_dir() -> PathBuf {
    repo_root().join("examples")
}

fn assert_real_native_wasm(output_file: &PathBuf) {
    let wat = fs::read_to_string(output_file.with_extension("wat")).unwrap();
    assert!(
        wat.contains("(func"),
        "expected native wasm function body, got:\n{wat}"
    );
}

#[test]
fn test_compile_simple() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("test.arg");
    fs::write(&source_file, "const x = 5;\nconsole.log(x);\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success()
        .stdout(predicate::str::contains("Parsing"))
        .stdout(predicate::str::contains("Type checking"))
        .stdout(predicate::str::contains("Borrow checking"))
        .stdout(predicate::str::contains("Generating JavaScript"))
        .stdout(predicate::str::contains("Done"));

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("Generated by Argon (IR)"));
    assert!(output.contains("const x = 5"));
    assert!(output.contains("console.log(x)"));
}

#[test]
fn test_compile_writes_source_map_when_enabled() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("sourcemap.arg");
    fs::write(&source_file, "const x = 5;\nconsole.log(x);\n").unwrap();

    let output_js = temp_dir.path().join("output.js");
    let output_map = temp_dir.path().join("output.js.map");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_js)
        .arg("--pipeline")
        .arg("ir")
        .arg("--source-map")
        .assert()
        .success();

    let js = fs::read_to_string(&output_js).unwrap();
    assert!(js.contains("sourceMappingURL=output.js.map"));

    let map = fs::read_to_string(&output_map).unwrap();
    assert!(map.contains("\"version\":3"));
}

#[test]
fn test_compile_try_catch_finally() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try.arg");
    fs::write(
        &source_file,
        "function f(): void { try { const x = 1; throw x; } catch (e) { const y = e; } finally { const z = 3; } }\nf();\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("try {"));
    assert!(output.contains("catch (e)"));
    assert!(output.contains("finally {"));
    assert!(output.contains("throw x"));
}

#[test]
fn test_compile_export_const() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("export_const.arg");
    fs::write(&source_file, "export const x = 1;\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("const x = 1;"));
    assert!(output.contains("export { x"));
}

#[test]
fn test_compile_opt_folds_exported_const() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("export_opt.arg");
    fs::write(&source_file, "const a = 1;\nexport const b = a + 2;\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .arg("--opt")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("const b = 3;"));
    assert!(output.contains("export { b"));
}

#[test]
fn test_argon_test_runs_esm_output() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("esm_test.arg");
    fs::write(
        &source_file,
        "export const x: number = 1;\nconsole.log(x);\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("test")
        .arg("--input")
        .arg(&source_file)
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();
}

#[test]
fn test_compile_logical_conditional_array_and_assignment() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("exprs.arg");
    fs::write(
        &source_file,
        "function f(a: i32, b: i32): i32 {\n    let x = 0;\n    x = a > b ? a : b;\n    const ok = (a > 0) && (b > 0);\n    const arr = [1, 2, 3];\n    if (ok) { return x + arr[0]; }\n    return x;\n}\nconsole.log(f(1, 2));\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("[1, 2, 3]"));
    assert!(output.contains("&&"));
    assert!(output.contains("?"));
    assert!(output.contains("x ="));
    assert!(output.contains("arr[0]"));
}

#[test]
fn test_compile_function() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("function.arg");
    fs::write(
        &source_file,
        "function add(a: number, b: number): number {\n    return a + b;\n}\nconsole.log(add(1, 2));\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("function add"));
}

#[test]
fn test_compile_struct() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("struct.arg");
    fs::write(
        &source_file,
        "struct Point {\n    x: number;\n    y: number;\n}\nconst p = Point { x: 1, y: 2 };\nconsole.log(p.x);\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("function Point(init)"));
    assert!(output.contains("this.x = init.x"));
    assert!(output.contains("this.y = init.y"));
    assert!(output.contains("new Point({ x: 1, y: 2 })"));
}

#[test]
fn test_check_validates_borrow_checker() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("borrow.arg");
    // This should compile successfully with borrow checking
    fs::write(
        &source_file,
        "function test(x: number): void {\n    const y = x;\n}\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("check").arg(&source_file).assert().success();
}

#[test]
fn test_compile_with_declarations() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("decl.arg");
    fs::write(
        &source_file,
        "function greet(name: string): string {\n    return \"Hello, \" + name;\n}\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--declarations")
        .assert()
        .success();

    let dts = fs::read_to_string(temp_dir.path().join("output.d.ts")).unwrap();
    assert!(dts.contains("greet"));
}

#[test]
fn test_compile_with_exported_generic_declarations() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("decl_export.arg");
    fs::write(
        &source_file,
        "export function identity<T>(value: T): T {\n    return value;\n}\n\nexport type Identity<T> = T;\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--declarations")
        .assert()
        .success();

    let dts = fs::read_to_string(temp_dir.path().join("output.d.ts")).unwrap();
    assert!(dts.contains("export declare function identity<T>(value: T): T;"));
    assert!(dts.contains("export type Identity<T> = T;"));
}

#[test]
fn test_invalid_syntax_fails() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("invalid.arg");
    fs::write(&source_file, "const x = ;\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .assert()
        .failure();
}

#[test]
fn test_help_output() {
    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("--help")
        .assert()
        .success()
        .stdout(predicate::str::contains("Argon"));
}

#[test]
fn test_compile_async_and_await() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("async.arg");
    fs::write(
        &source_file,
        "async function greet(): string {\n    return \"hello\";\n}\nasync function main(): string {\n    const result = await greet();\n    return result;\n}\n",
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("async function greet"));
    assert!(output.contains("async function main"));
    assert!(output.contains("await greet()"));
}

#[test]
fn test_compile_jsx() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("jsx.arg");
    fs::write(&source_file, "<div className=\"test\">Hello</div>\n").unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(temp_dir.path().join("output.js"))
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("output.js")).unwrap();
    assert!(output.contains("React.createElement"));
    assert!(output.contains("\"div\""));
    assert!(output.contains("className"));
    assert!(output.contains("\"Hello\""));
}

#[test]
fn test_compile_example_control_flow_uses_cfg_in_ir() {
    let temp_dir = tempfile::tempdir().unwrap();
    let example = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("examples")
        .join("control-flow.arg");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&example)
        .arg("--pipeline")
        .arg("ir")
        .arg("-o")
        .arg(temp_dir.path().join("out.js"))
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("out.js")).unwrap();
    // The IR CFG emitter uses a bb state machine.
    assert!(output.contains("switch (__bb)"));
    assert!(output.contains("console.log(loopCount)"));
}

#[test]
fn test_compile_example_esm_import() {
    let temp_dir = tempfile::tempdir().unwrap();
    let example = PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("..")
        .join("examples")
        .join("esm.arg");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&example)
        .arg("--pipeline")
        .arg("ir")
        .arg("-o")
        .arg(temp_dir.path().join("out.js"))
        .assert()
        .success();

    let output = fs::read_to_string(temp_dir.path().join("out.js")).unwrap();
    assert!(output.contains("import \"reflect-metadata\";"));
    assert!(output.contains("import axios from \"axios\";"));
    assert!(output.contains("import { useState } from \"react\";"));
    assert!(output.contains("const apiBase = \"/api\""));
}

#[test]
fn test_check_readme_interop_annotations() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("interop.arg");
    fs::write(
        &source_file,
        r#"
@js-interop
declare module "axios" {
    function get<T>(url: string): string;
}

@export
function processImage(data: i32, width: i32, height: i32): i32 {
    return data + width + height;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("check").arg(&source_file).assert().success();
}

#[test]
fn test_compile_ir_and_execute_for_of_snippet() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("for_of.arg");
    let output_file = temp_dir.path().join("output.js");
    fs::write(
        &source_file,
        r#"
function renderAll(items: i32[]): i32 {
    let sum = 0;
    for (const item of items) {
        sum = sum + item;
    }
    return sum;
}

console.log(renderAll([1, 2, 3]));
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let node_output = Command::new("node").arg(&output_file).output().unwrap();
    assert!(node_output.status.success());
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("6"));
}

#[test]
fn test_run_executes_for_of_runtime_snippet() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("run_for_of.arg");
    fs::write(
        &source_file,
        r#"
const items = [1, 2, 3];
let sum = 0;
for (const item of items) {
    sum = sum + item;
}
console.log(sum);
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("run")
        .arg(&source_file)
        .assert()
        .success()
        .stdout(predicate::str::contains("6"));
}

#[test]
fn test_compile_wasm_subset_and_execute() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("subset.arg");
    let output_file = temp_dir.path().join("subset.wasm");
    fs::write(
        &source_file,
        r#"
function sumTo(n: i32): i32 {
    let acc = 0;
    let i = 0;
    while (i <= n) {
        acc = acc + i;
        i = i + 1;
    }
    return acc;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success()
        .stdout(predicate::str::contains("Generating WebAssembly"));

    assert_real_native_wasm(&output_file);

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(String(instance.exports.sumTo(5)));
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success());
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("15"));
}

#[test]
fn test_compile_wasm_writes_loader_sidecar() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("loader.arg");
    let output_file = temp_dir.path().join("loader.wasm");
    fs::write(
        &source_file,
        r#"
function greet(): string {
    return "hello";
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let loader_file = output_file.with_extension("mjs");
    let host_file = output_file.with_extension("host.mjs");
    let loader_contents = fs::read_to_string(&loader_file).unwrap();
    assert!(host_file.exists());
    assert!(loader_contents.contains("instantiateArgon"));
    assert!(loader_contents.contains("loader.wasm"));
    assert!(loader_contents.contains("loader.host.mjs"));

    let script_file = temp_dir.path().join("check_loader.mjs");
    fs::write(
        &script_file,
        r#"
import { instantiateArgon } from "./loader.mjs";

const runtime = await instantiateArgon();
console.log(runtime.readString(runtime.exports.greet()));
"#,
    )
    .unwrap();

    let node_output = Command::new("node").arg(&script_file).output().unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("hello"));
}

#[test]
fn test_compile_wasm_async_executes_via_host_sidecar() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("async_loader.arg");
    let output_file = temp_dir.path().join("async_loader.wasm");
    fs::write(
        &source_file,
        r#"
async function greet(): string {
    return "hello";
}

async function main(): string {
    const value = await greet();
    return value;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script_file = temp_dir.path().join("run_async_loader.mjs");
    fs::write(
        &script_file,
        r#"
import { instantiateArgon } from "./async_loader.mjs";

const runtime = await instantiateArgon();
console.log(await runtime.exports.main());
"#,
    )
    .unwrap();

    let node_output = Command::new("node").arg(&script_file).output().unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("hello"));
}

#[test]
fn test_compile_wasm_async_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("async_native.arg");
    let output_file = temp_dir.path().join("async_native.wasm");
    fs::write(
        &source_file,
        r#"
async function greet(): string {
    return "hello";
}

async function main(): string {
    const value = await greet();
    return value;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    assert_real_native_wasm(&output_file);

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);

function readString(memory, ptr) {
  const view = new DataView(memory.buffer);
  const len = view.getUint32(ptr, true);
  return new TextDecoder().decode(new Uint8Array(memory.buffer, ptr + 4, len));
}

WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(readString(instance.exports.memory, instance.exports.main()));
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("hello"));
}

#[test]
fn test_compile_wasm_try_catch_executes_via_host_sidecar() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try_loader.arg");
    let output_file = temp_dir.path().join("try_loader.wasm");
    fs::write(
        &source_file,
        r#"
function recover(flag: bool): i32 {
    try {
        if (flag) {
            throw 7;
        }
        return 1;
    } catch (err) {
        return 0;
    }

    return 0;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script_file = temp_dir.path().join("run_try_loader.mjs");
    fs::write(
        &script_file,
        r#"
import { instantiateArgon } from "./try_loader.mjs";

const runtime = await instantiateArgon();
console.log(`${runtime.exports.recover(false)},${runtime.exports.recover(true)}`);
"#,
    )
    .unwrap();

    let node_output = Command::new("node").arg(&script_file).output().unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("1,0"));
}

#[test]
fn test_compile_wasm_try_catch_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try_native.arg");
    let output_file = temp_dir.path().join("try_native.wasm");
    fs::write(
        &source_file,
        r#"
function recover(): i32 {
    let value = 1;
    try {
        throw 7;
    } catch (err) {
        value = err;
    }
    return value;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(String(instance.exports.recover()));
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("7"));
}

#[test]
fn test_compile_wasm_structured_try_catch_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try_structured_native.arg");
    let output_file = temp_dir.path().join("try_structured_native.wasm");
    fs::write(
        &source_file,
        r#"
function recover(flag: bool): i32 {
    try {
        if (flag) {
            throw 7;
        }
        return 1;
    } catch (err) {
        return 0;
    }

    return 0;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(`${instance.exports.recover(0)},${instance.exports.recover(1)}`);
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("1,0"));
}

#[test]
fn test_compile_wasm_loop_control_inside_try_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try_loop_native.arg");
    let output_file = temp_dir.path().join("try_loop_native.wasm");
    fs::write(
        &source_file,
        r#"
function countUntil(limit: i32): i32 {
    let i = 0;
    try {
        while (i < limit) {
            i = i + 1;
            if (i == 2) {
                continue;
            }
            if (i == 4) {
                break;
            }
        }
    } finally {
        const done = true;
    }

    return i;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(`${instance.exports.countUntil(3)},${instance.exports.countUntil(10)}`);
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("3,4"));
}

#[test]
fn test_compile_wasm_for_of_inside_try_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try_for_of_native.arg");
    let output_file = temp_dir.path().join("try_for_of_native.wasm");
    fs::write(
        &source_file,
        r#"
function sumUntil(): i32 {
    let sum = 0;
    try {
        const items = [2, 3, 4, 5];
        for (const item of items) {
            sum = sum + item;
            if (sum > 6) {
                break;
            }
        }
    } finally {
        const done = true;
    }

    return sum;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(String(instance.exports.sumUntil()));
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("9"));
}

#[test]
fn test_compile_wasm_switch_and_match_inside_try_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("try_switch_match_native.arg");
    let output_file = temp_dir.path().join("try_switch_match_native.wasm");
    fs::write(
        &source_file,
        r#"
function choose(x: i32): i32 {
    let value = 0;
    try {
        switch (x) {
            case 1:
                value = 10;
                break;
            case 2:
                value = 20;
                break;
            default:
                value = 30;
        }
    } finally {
        const done = true;
    }

    return value;
}

function classify(x: i32): i32 {
    let value = 0;
    try {
        match (x) {
            1 => value = 100,
            2 => value = 200,
        }
    } finally {
        const done = true;
    }

    return value;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(`${instance.exports.choose(1)},${instance.exports.choose(5)},${instance.exports.classify(2)},${instance.exports.classify(9)}`);
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("10,30,200,0"));
}

#[test]
fn test_compile_wasm_import_executes_via_host_sidecar() {
    let temp_dir = tempfile::tempdir().unwrap();
    let dep_file = temp_dir.path().join("dep.mjs");
    let source_file = temp_dir.path().join("interop_loader.arg");
    let output_file = temp_dir.path().join("interop_loader.wasm");
    fs::write(
        &dep_file,
        "export default function inc(x) { return x + 1; }\n",
    )
    .unwrap();
    fs::write(
        &source_file,
        r#"
import inc from "./dep.mjs";

function main(): i32 {
    return inc(4);
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script_file = temp_dir.path().join("run_interop_loader.mjs");
    fs::write(
        &script_file,
        r#"
import { instantiateArgon } from "./interop_loader.mjs";

const runtime = await instantiateArgon({
  "./dep.mjs": {
    default(x) {
      return x + 1;
    }
  }
});
console.log(runtime.exports.main());
"#,
    )
    .unwrap();

    let node_output = Command::new("node").arg(&script_file).output().unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("5"));
}

#[test]
fn test_compile_wasm_import_executes_standalone() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("interop_native.arg");
    let output_file = temp_dir.path().join("interop_native.wasm");
    fs::write(
        &source_file,
        r#"
import inc from "./dep.mjs";

function main(): i32 {
    return inc(4);
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {
  "./dep.mjs": {
    default(x) {
      return x + 1;
    }
  }
}).then(({ instance }) => {
  console.log(String(instance.exports.main()));
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("5"));
}

#[test]
fn test_readme_js_examples_compile_on_ir_pipeline() {
    let cases = [
        (
            "enum.arg",
            Some("const Mode = { Dev: 0, Test: 1, Prod: 2 }"),
        ),
        ("functions.arg", Some("function reduceThree")),
        ("generic_simple.arg", Some("function Container")),
        ("interface.arg", Some("function useReader")),
        ("interop.arg", Some("function processImage")),
        ("test_lexer.arg", Some("function makeMessage")),
        (
            "type_test.arg",
            Some("const Status = { Ready: 0, Running: 1, Done: 2 }"),
        ),
    ];

    for (file_name, expected_snippet) in cases {
        let temp_dir = tempfile::tempdir().unwrap();
        let output_file = temp_dir.path().join("out.js");
        let source_file = examples_dir().join(file_name);

        let mut cmd = cargo_bin_cmd!("argon");
        cmd.arg("compile")
            .arg(&source_file)
            .arg("--target")
            .arg("js")
            .arg("--pipeline")
            .arg("ir")
            .arg("-o")
            .arg(&output_file)
            .assert()
            .success();

        let output = fs::read_to_string(&output_file).unwrap();
        if let Some(expected_snippet) = expected_snippet {
            assert!(
                output.contains(expected_snippet),
                "expected `{expected_snippet}` in output for {file_name}, got:\n{output}"
            );
        }
    }
}

#[test]
fn test_run_core_examples_succeed_after_runtime_fixes() {
    let cases = [
        "classes.arg",
        "generic_simple2.arg",
        "recursion.arg",
        "type_test.arg",
    ];

    for file_name in cases {
        let source_file = examples_dir().join(file_name);
        let mut cmd = cargo_bin_cmd!("argon");
        cmd.arg("run").arg(&source_file).assert().success();
    }
}

#[test]
fn test_run_compile_only_examples_fail_with_clear_diagnostic() {
    let cases = ["jsx.arg", "jsx_simple.arg", "esm.arg"];

    for file_name in cases {
        let source_file = examples_dir().join(file_name);
        let mut cmd = cargo_bin_cmd!("argon");
        cmd.arg("run")
            .arg(&source_file)
            .assert()
            .failure()
            .stderr(predicate::str::contains("Compile-only feature"));
    }
}

#[test]
fn test_compile_wasm_fails_for_unsupported_native_example() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = examples_dir().join("enum.arg");
    let output_file = temp_dir.path().join("enum.wasm");

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .failure()
        .stderr(predicate::str::contains("Unsupported"));
}

#[test]
fn test_compile_wasm_struct_literal_member_access() {
    let temp_dir = tempfile::tempdir().unwrap();
    let source_file = temp_dir.path().join("struct_member.arg");
    let output_file = temp_dir.path().join("struct_member.wasm");
    fs::write(
        &source_file,
        r#"
struct Point {
    x: i32;
    y: i32;
}

function getX(): i32 {
    const point = Point { x: 6, y: 8 };
    return point.x;
}
"#,
    )
    .unwrap();

    let mut cmd = cargo_bin_cmd!("argon");
    cmd.arg("compile")
        .arg(&source_file)
        .arg("-o")
        .arg(&output_file)
        .arg("--target")
        .arg("wasm")
        .arg("--pipeline")
        .arg("ir")
        .assert()
        .success();

    let script = r#"
const fs = require('fs');
const wasmPath = process.argv[1];
const bytes = fs.readFileSync(wasmPath);
WebAssembly.instantiate(bytes, {}).then(({ instance }) => {
  console.log(String(instance.exports.getX()));
}).catch((err) => {
  console.error(err);
  process.exit(1);
});
"#;
    let node_output = Command::new("node")
        .arg("-e")
        .arg(script)
        .arg(&output_file)
        .output()
        .unwrap();
    assert!(node_output.status.success(), "{:?}", node_output);
    let stdout = String::from_utf8_lossy(&node_output.stdout);
    assert!(stdout.contains("6"));
}
